import { Reply } from '@/lib/forum-types';

const r = (
  echo: number,
  dive: number,
  ripple: number,
  witness: number,
  signal: number,
) => ({ echo, dive, ripple, witness, signal });

export const REPLY_SEED: Record<string, Reply[]> = {
  'th-001': [
    {
      id: 'th-001-r1',
      threadId: 'th-001',
      postNumber: 2,
      body: '> three lights held position perfectly\n\nthat formation does not happen naturally. controlled movement. equidistant spacing like that requires intent.',
      createdAt: '2 hours ago',
      authorHandle: 'STATIC_VEIL',
      authorMode: 'ghost',
      reactions: r(12, 4, 6, 9, 2),
    },
    {
      id: 'th-001-r2',
      threadId: 'th-001',
      postNumber: 3,
      body: 'scanner blackouts last three minutes on average for interference events. longer than that usually means active suppression or equipment fault. three minutes is the edge.',
      createdAt: '1 hour 48 min ago',
      authorHandle: 'ANON',
      authorMode: 'anon',
      reactions: r(8, 1, 4, 5, 1),
    },
    {
      id: 'th-001-r3',
      threadId: 'th-001',
      postNumber: 4,
      body: '> water stayed still the whole time\n\nthis is the part nobody talks about. local wind and surface movement should have continued. something was affecting local physics or it was very high altitude.',
      createdAt: '1 hour 40 min ago',
      authorHandle: 'SIGNAL_BLEED',
      authorMode: 'ghost',
      reactions: r(19, 7, 11, 14, 3),
    },
    {
      id: 'th-001-r4',
      threadId: 'th-001',
      postNumber: 5,
      body: 'what time exactly. not asking to debunk. asking because reservoir events cluster around the same window. checking a pattern.',
      createdAt: '1 hour 22 min ago',
      authorHandle: 'UNKNOWN NODE',
      authorMode: 'anon',
      reactions: r(6, 0, 3, 4, 1),
    },
    {
      id: 'th-001-r5',
      threadId: 'th-001',
      postNumber: 6,
      body: '> county scanner went dead\n\nhad this happen twice in different counties. once before the lights appeared, once after. not sure which is stranger.',
      createdAt: '1 hour 5 min ago',
      authorHandle: 'NULL_RELAY',
      authorMode: 'ghost',
      reactions: r(15, 5, 9, 11, 2),
    },
    {
      id: 'th-001-r6',
      threadId: 'th-001',
      postNumber: 7,
      body: 'waiting for the frames. also waiting for any record of who owns the property around that reservoir. county records sometimes get interesting after events like this.',
      createdAt: '44 min ago',
      authorHandle: 'GHOST',
      authorMode: 'anon',
      reactions: r(7, 2, 3, 5, 1),
    },
    {
      id: 'th-001-r7',
      threadId: 'th-001',
      postNumber: 8,
      body: '> frames posted\n\nlooked at stills three times. the light at the lower position has no reflection in the water even when the other two do. that is not a lens artifact.',
      createdAt: '31 min ago',
      authorHandle: 'FRAGMENT_08',
      authorMode: 'ghost',
      reactions: r(24, 9, 16, 18, 5),
    },
    {
      id: 'th-001-r8',
      threadId: 'th-001',
      postNumber: 9,
      body: 'northdrift here. the third light was the one that moved. not the two outer ones. and the third stopped at exactly the waterline. not above it. exactly at it.',
      createdAt: '18 min ago',
      authorHandle: 'northdrift_anon',
      authorMode: 'ghost',
      reactions: r(32, 11, 21, 26, 7),
    },
  ],

  'th-002': [
    {
      id: 'th-002-r1',
      threadId: 'th-002',
      postNumber: 2,
      body: 'which county. asking because I track permit record changes in about fourteen counties and the scrubbing happens in specific batches. yours might match a known window.',
      createdAt: '45 min ago',
      authorHandle: 'LEDGER_NODE',
      authorMode: 'ghost',
      reactions: r(9, 3, 5, 7, 1),
    },
    {
      id: 'th-002-r2',
      threadId: 'th-002',
      postNumber: 3,
      body: '> same documents same stamps different owners\n\nthis is not laziness. somebody knows how archive crawlers work and is timing edits between snapshot windows.',
      createdAt: '38 min ago',
      authorHandle: 'ARCHIVE_SIFT',
      authorMode: 'ghost',
      reactions: r(14, 4, 8, 10, 2),
    },
    {
      id: 'th-002-r3',
      threadId: 'th-002',
      postNumber: 4,
      body: 'the web archive has a known gap problem where some mirrors are only crawled every 90 days. anyone doing targeted changes knows exactly which records fall through that window.',
      createdAt: '29 min ago',
      authorHandle: 'ANON',
      authorMode: 'anon',
      reactions: r(11, 3, 6, 8, 1),
    },
    {
      id: 'th-002-r4',
      threadId: 'th-002',
      postNumber: 5,
      body: '> county records from 1998\n\nsaw the same thing with zoning documents from 2001 in a different state. permits disappeared between captures. ownership history just stops. then restarts clean.',
      createdAt: '11 min ago',
      authorHandle: 'NULL_RELAY',
      authorMode: 'ghost',
      reactions: r(17, 6, 10, 12, 3),
    },
  ],

  'th-003': [
    {
      id: 'th-003-r1',
      threadId: 'th-003',
      postNumber: 2,
      body: 'yes. same station. tiled walls are tan and white alternating, large format. the fluorescents hum in groups not continuously. I stopped going past the second tunnel.',
      createdAt: '14 min ago',
      authorHandle: 'SLEEP_RELAY',
      authorMode: 'ghost',
      reactions: r(18, 7, 14, 12, 2),
    },
    {
      id: 'th-003-r2',
      threadId: 'th-003',
      postNumber: 3,
      body: '> same fourth tunnel\n\nthere are only three tunnels when you arrive. the fourth one appears after you have been on the platform long enough. I do not know what triggers it.',
      createdAt: '13 min ago',
      authorHandle: 'FRAGMENT_08',
      authorMode: 'ghost',
      reactions: r(22, 9, 17, 15, 3),
    },
    {
      id: 'th-003-r3',
      threadId: 'th-003',
      postNumber: 4,
      body: 'i have the platform map. the fourth tunnel is on the left side of the platform, past where the lighting stops. I drew it from memory twice on different nights and they match.',
      createdAt: '11 min ago',
      authorHandle: 'UNKNOWN NODE',
      authorMode: 'anon',
      reactions: r(25, 10, 19, 17, 4),
    },
    {
      id: 'th-003-r4',
      threadId: 'th-003',
      postNumber: 5,
      body: 'asked three people in my life about this without explaining. two of them went quiet. one said she stopped having the dream after she went into the fourth tunnel.',
      createdAt: '9 min ago',
      authorHandle: 'MEMORYLEAK',
      authorMode: 'ghost',
      reactions: r(29, 12, 22, 20, 5),
    },
    {
      id: 'th-003-r5',
      threadId: 'th-003',
      postNumber: 6,
      body: '> soot on my sleeve\n\nthere is a smell. like ozone and old paper. I notice it most when I remember the dream in a non-dream context. like right now.',
      createdAt: '7 min ago',
      authorHandle: 'GHOST',
      authorMode: 'anon',
      reactions: r(34, 14, 25, 22, 6),
    },
    {
      id: 'th-003-r6',
      threadId: 'th-003',
      postNumber: 7,
      body: 'sleeprelay here. that is the same smell. ozone and old paper. I have had the dream 34 times. I have the fourth tunnel in my map but I have never gone through it. something feels like a rule.',
      createdAt: '5 min ago',
      authorHandle: 'sleeprelay',
      authorMode: 'ghost',
      reactions: r(41, 18, 30, 28, 8),
    },
  ],

  'th-004': [
    {
      id: 'th-004-r1',
      threadId: 'th-004',
      postNumber: 2,
      body: 'what is the frequency of the tone. not the note, the Hz value. this matters for the comparison.',
      createdAt: '1 hour 12 min ago',
      authorHandle: 'ANON',
      authorMode: 'anon',
      reactions: r(6, 2, 4, 5, 1),
    },
    {
      id: 'th-004-r2',
      threadId: 'th-004',
      postNumber: 3,
      body: '> waveform posted\n\nlooked at it. the ATM error tone is normally a synthetic 880Hz burst. what you posted is 880Hz with a second harmonic at 440Hz that should not be there. that is not standard firmware.',
      createdAt: '58 min ago',
      authorHandle: 'GLITCH_DIET',
      authorMode: 'ghost',
      reactions: r(21, 8, 14, 17, 4),
    },
    {
      id: 'th-004-r3',
      threadId: 'th-004',
      postNumber: 4,
      body: 'the continuity loss is the more important detail. how long is four seconds for you subjectively. is it instantaneous or a slow fade.',
      createdAt: '47 min ago',
      authorHandle: 'NULL_RELAY',
      authorMode: 'ghost',
      reactions: r(14, 5, 9, 11, 2),
    },
    {
      id: 'th-004-r4',
      threadId: 'th-004',
      postNumber: 5,
      body: 'breakpoint here. the four seconds feel like nothing. no fade, no blur. just before and after with nothing between. the before moment is always mid-transaction.',
      createdAt: '39 min ago',
      authorHandle: 'breakpoint_sleep',
      authorMode: 'ghost',
      reactions: r(28, 11, 18, 21, 5),
    },
    {
      id: 'th-004-r5',
      threadId: 'th-004',
      postNumber: 6,
      body: 'this reads like absence seizure symptomology triggered by a specific audio cue. not dismissing the strangeness. just noting that the mechanism might be neurological rather than external.',
      createdAt: '31 min ago',
      authorHandle: 'ANON',
      authorMode: 'anon',
      reactions: r(9, 3, 6, 7, 1),
    },
    {
      id: 'th-004-r6',
      threadId: 'th-004',
      postNumber: 7,
      body: '> it is the same\n\nI matched the same harmonic pattern to a tone used in early emergency broadcast test sequences. the band was retired in the nineties. I do not know how it ended up in that machine.',
      createdAt: '22 min ago',
      authorHandle: 'SIGNAL_BLEED',
      authorMode: 'ghost',
      reactions: r(34, 14, 22, 26, 7),
    },
    {
      id: 'th-004-r7',
      threadId: 'th-004',
      postNumber: 8,
      body: 'I have the same reaction to one specific ringtone. not all ringtones. one specific one. I do not know which phone it is. I just stop wherever I am and lose the window.',
      createdAt: '11 min ago',
      authorHandle: 'FRAGMENT_08',
      authorMode: 'ghost',
      reactions: r(19, 7, 13, 15, 3),
    },
  ],

  'th-005': [
    {
      id: 'th-005-r1',
      threadId: 'th-005',
      postNumber: 2,
      body: 'I think I remember this. the moth banner was dark blue, not black. threads were numbered in hex. I only visited twice and both times the thread count was different.',
      createdAt: '55 min ago',
      authorHandle: 'DEAD_CHANNEL',
      authorMode: 'ghost',
      reactions: r(11, 3, 8, 9, 2),
    },
    {
      id: 'th-005-r2',
      threadId: 'th-005',
      postNumber: 3,
      body: '> locked themselves at sunrise\n\nthere was a different one like this that I remember. forum had a visible countdown timer in the corner. when it hit zero the threads were gone. refreshing just gave you the index.',
      createdAt: '48 min ago',
      authorHandle: 'COPPER_NODE',
      authorMode: 'ghost',
      reactions: r(14, 4, 10, 11, 2),
    },
    {
      id: 'th-005-r3',
      threadId: 'th-005',
      postNumber: 4,
      body: 'the ISP subdomain thing is key. most of those were earthlink or mindspring regional hosting from around 1999 to 2003. dead ISP directories sometimes still have partial listings if you know where to look.',
      createdAt: '37 min ago',
      authorHandle: 'ANON',
      authorMode: 'anon',
      reactions: r(9, 2, 6, 7, 1),
    },
    {
      id: 'th-005-r4',
      threadId: 'th-005',
      postNumber: 5,
      body: 'ran some archive searches. found a ghost domain on a dead mindspring mirror with a banner image that is a broken image tag. the alt text is just "after hours". no other files cached.',
      createdAt: '19 min ago',
      authorHandle: 'ARCHIVE_SIFT',
      authorMode: 'ghost',
      reactions: r(18, 7, 13, 14, 3),
    },
  ],

  'th-006': [
    {
      id: 'th-006-r1',
      threadId: 'th-006',
      postNumber: 2,
      body: 'you said somebody answered on the third ring and knew the tx hash. was it the full hash or just part of it. the last six digits is a very specific kind of knowledge.',
      createdAt: '1 hour 18 min ago',
      authorHandle: 'NULL_RELAY',
      authorMode: 'ghost',
      reactions: r(14, 5, 9, 11, 2),
    },
    {
      id: 'th-006-r2',
      threadId: 'th-006',
      postNumber: 3,
      body: '> not posting the number\n\ngood. do not post the number. ever. if they knew the hash before you spoke they already know more than the hash.',
      createdAt: '1 hour 4 min ago',
      authorHandle: 'STATIC_VEIL',
      authorMode: 'ghost',
      reactions: r(22, 9, 15, 18, 4),
    },
    {
      id: 'th-006-r3',
      threadId: 'th-006',
      postNumber: 4,
      body: '> arcade owner denies the booth exists\n\nof course they do. check the building permits. phone infrastructure requires a permit even for a payphone booth in a private business.',
      createdAt: '47 min ago',
      authorHandle: 'LEDGER_NODE',
      authorMode: 'ghost',
      reactions: r(17, 6, 11, 13, 3),
    },
    {
      id: 'th-006-r4',
      threadId: 'th-006',
      postNumber: 5,
      body: 'the wallet trail ending at a physical phone is interesting on its own. that means there was a bridge somewhere. either the phone had network access or somebody physically monitored the mempool.',
      createdAt: '33 min ago',
      authorHandle: 'ANON',
      authorMode: 'anon',
      reactions: r(29, 11, 19, 22, 5),
    },
    {
      id: 'th-006-r5',
      threadId: 'th-006',
      postNumber: 6,
      body: 'a friend of mine had something similar three years ago. different city, different chain. transaction settled and someone left a physical note under his door within twelve hours. he moved two weeks later.',
      createdAt: '21 min ago',
      authorHandle: 'GHOST',
      authorMode: 'anon',
      reactions: r(35, 14, 24, 27, 7),
    },
    {
      id: 'th-006-r6',
      threadId: 'th-006',
      postNumber: 7,
      body: 'ashtray here. went back to the arcade location. the booth is gone. not moved. no mount points on the floor. no conduit. it was never there or the floor was replaced. I did not stay long.',
      createdAt: '8 min ago',
      authorHandle: 'ashtrayoracle',
      authorMode: 'ghost',
      reactions: r(52, 21, 38, 41, 12),
    },
  ],

  'th-007': [
    {
      id: 'th-007-r1',
      threadId: 'th-007',
      postNumber: 2,
      body: 'yes. I remember threads that read like oral history transcripts. very formal. never first person. always attributed to someone unknown. felt like reading collected folklore.',
      createdAt: '36 min ago',
      authorHandle: 'DEAD_CHANNEL',
      authorMode: 'ghost',
      reactions: r(10, 3, 7, 8, 1),
    },
    {
      id: 'th-007-r2',
      threadId: 'th-007',
      postNumber: 3,
      body: '> vanished every equinox\n\nI thought that was a moderation choice at first. then I realized the equinox timing was documented in the threads themselves. the board was aware of its own cycle.',
      createdAt: '27 min ago',
      authorHandle: 'ARCHIVE_SIFT',
      authorMode: 'ghost',
      reactions: r(16, 6, 11, 12, 3),
    },
    {
      id: 'th-007-r3',
      threadId: 'th-007',
      postNumber: 4,
      body: 'the writing style you are describing was more common on forums that required manual approval to post. made every post feel like it had been considered. no throwaway content.',
      createdAt: '14 min ago',
      authorHandle: 'ANON',
      authorMode: 'anon',
      reactions: r(8, 2, 5, 6, 1),
    },
    {
      id: 'th-007-r4',
      threadId: 'th-007',
      postNumber: 5,
      body: 'I have what might be a cached thread from it. saved it years ago because of the writing. it describes a room in a building that may or may not exist. the details are very precise. let me find the file.',
      createdAt: '5 min ago',
      authorHandle: 'COPPER_NODE',
      authorMode: 'ghost',
      reactions: r(21, 8, 15, 16, 4),
    },
  ],

  'th-008': [
    {
      id: 'th-008-r1',
      threadId: 'th-008',
      postNumber: 2,
      body: 'this happened with obituaries too. same text appeared in four regional papers for someone with different names and dates. the background paragraphs were identical.',
      createdAt: '52 min ago',
      authorHandle: 'ANON',
      authorMode: 'anon',
      reactions: r(11, 3, 7, 9, 2),
    },
    {
      id: 'th-008-r2',
      threadId: 'th-008',
      postNumber: 3,
      body: 'ledger here. found a fourth clipping. different state. same quote, slightly different punctuation. like it was retyped rather than copied. somebody was transcribing from a source.',
      createdAt: '43 min ago',
      authorHandle: 'ledgerghost',
      authorMode: 'ghost',
      reactions: r(17, 6, 11, 13, 3),
    },
    {
      id: 'th-008-r3',
      threadId: 'th-008',
      postNumber: 4,
      body: 'the syndication desk explanation is the boring answer. the interesting answer is that these papers all used the same stringer for local coverage. one person, multiple bylines, one source.',
      createdAt: '29 min ago',
      authorHandle: 'NULL_RELAY',
      authorMode: 'ghost',
      reactions: r(14, 5, 9, 11, 2),
    },
    {
      id: 'th-008-r4',
      threadId: 'th-008',
      postNumber: 5,
      body: 'the fourth paper using a slightly different punctuation version is the detail that matters. that means the source text was modified between uses. that is not syndication.',
      createdAt: '12 min ago',
      authorHandle: 'FRAGMENT_08',
      authorMode: 'ghost',
      reactions: r(19, 7, 13, 14, 3),
    },
  ],
  'th-009': [
    {
      id: 'th-009-r1',
      threadId: 'th-009',
      postNumber: 2,
      body: 'the detail about the well filled with river stones is very specific. that is not an architectural feature someone invents. that is something a person saw or was told about by someone who saw it.',
      createdAt: '2 hours ago',
      authorHandle: 'FRAGMENT_08',
      authorMode: 'ghost',
      reactions: r(14, 5, 9, 11, 2),
    },
    {
      id: 'th-009-r2',
      threadId: 'th-009',
      postNumber: 3,
      body: 'I have a similar situation with a farmhouse my grandfather described in detail. the location matches a structure that county records show burned in 1963. the structure in the satellite image from 2018 has the same roofline he drew for me.',
      createdAt: '1 hour 42 min ago',
      authorHandle: 'NULL_RELAY',
      authorMode: 'ghost',
      reactions: r(21, 7, 14, 17, 3),
    },
    {
      id: 'th-009-r3',
      threadId: 'th-009',
      postNumber: 4,
      body: '> she died in 1991\n\nthe question I keep asking in cases like this is not whether the building exists. the question is how the knowledge transferred.',
      createdAt: '1 hour 18 min ago',
      authorHandle: 'ANON',
      authorMode: 'anon',
      reactions: r(18, 6, 12, 14, 2),
    },
    {
      id: 'th-009-r4',
      threadId: 'th-009',
      postNumber: 5,
      body: 'I tried to locate the church archive you mentioned. the diocesan records from that region for 1987 have a three-month gap. not redacted. just absent. the archivist said it was a filing error.',
      createdAt: '48 min ago',
      authorHandle: 'ARCHIVE_SIFT',
      authorMode: 'ghost',
      reactions: r(27, 9, 18, 21, 4),
    },
    {
      id: 'th-009-r5',
      threadId: 'th-009',
      postNumber: 6,
      body: '> sold to an unknown private party\n\nthat classification is unusual for a religious property transfer. church sales are typically public record with named buyers. an unknown party suggests the transaction was structured to avoid that requirement.',
      createdAt: '31 min ago',
      authorHandle: 'LEDGER_NODE',
      authorMode: 'ghost',
      reactions: r(32, 11, 21, 25, 5),
    },
  ],

  'th-010': [
    {
      id: 'th-010-r1',
      threadId: 'th-010',
      postNumber: 2,
      body: 'the names being ordinary is the detail that bothers me most. a PSA reading out celebrity names is a known format. reading lists of ordinary names is not. that is not a recognized broadcast structure from that period.',
      createdAt: '4 hours ago',
      authorHandle: 'DEAD_CHANNEL',
      authorMode: 'ghost',
      reactions: r(16, 5, 10, 13, 2),
    },
    {
      id: 'th-010-r2',
      threadId: 'th-010',
      postNumber: 3,
      body: 'I had a different broadcast anomaly from around the same period. local channel, late night. regular programming interrupted by what looked like a standard public service announcement card — colored bars and a tone — but it lasted 22 minutes. no station ID at the end.',
      createdAt: '3 hours ago',
      authorHandle: 'ANON',
      authorMode: 'anon',
      reactions: r(12, 3, 8, 10, 1),
    },
    {
      id: 'th-010-r3',
      threadId: 'th-010',
      postNumber: 4,
      body: '> two people remembered it independently\n\nthis is the important detail. independent recollection of an unusual broadcast without prior discussion. if both witnesses were not in contact, the probability of shared confabulation drops significantly.',
      createdAt: '2 hours ago',
      authorHandle: 'NULL_RELAY',
      authorMode: 'ghost',
      reactions: r(19, 6, 12, 15, 3),
    },
    {
      id: 'th-010-r4',
      threadId: 'th-010',
      postNumber: 5,
      body: 'third witness here. I saw it. It aired during the 2AM slot on a network affiliate I watched regularly. The names were read slowly, one every four seconds. I stopped counting after thirty. I remember it felt like a roll call for something that had not happened yet.',
      createdAt: '1 hour ago',
      authorHandle: 'GHOST',
      authorMode: 'anon',
      reactions: r(38, 14, 26, 30, 7),
    },
  ],

  'th-012': [
    {
      id: 'th-012-r1',
      threadId: 'th-012',
      postNumber: 2,
      body: 'the ink remaining damp is physically unusual. even inks formulated for moisture retention would dry in days under standard archival conditions, not weeks in a sealed box.',
      createdAt: '3 hours ago',
      authorHandle: 'FRAGMENT_08',
      authorMode: 'ghost',
      reactions: r(17, 6, 11, 14, 2),
    },
    {
      id: 'th-012-r2',
      threadId: 'th-012',
      postNumber: 3,
      body: '> not in any language I can identify\n\ncan you describe the script direction and whether the characters are connected or discrete. that would narrow the language family significantly even if the specific language is unknown.',
      createdAt: '2 hours ago',
      authorHandle: 'ANON',
      authorMode: 'anon',
      reactions: r(9, 3, 6, 7, 1),
    },
    {
      id: 'th-012-r3',
      threadId: 'th-012',
      postNumber: 4,
      body: '> pages 88 and 144\n\nthose page numbers are not random if this is a religious or hermetic text. 88 is frequently associated with specific numerological traditions. 144 appears in several eschatological frameworks. someone knew the page structure before they wrote.',
      createdAt: '1 hour ago',
      authorHandle: 'ARCHIVE_SIFT',
      authorMode: 'ghost',
      reactions: r(24, 8, 16, 19, 4),
    },
    {
      id: 'th-012-r4',
      threadId: 'th-012',
      postNumber: 5,
      body: 'I work in a university archive. we have had three cases of wet ink in sealed materials in the last twelve years. all three were in donated collections from the same county. all three involved notation that predated the enclosing document by at least fifty years.',
      createdAt: '44 min ago',
      authorHandle: 'NULL_RELAY',
      authorMode: 'ghost',
      reactions: r(31, 11, 21, 26, 6),
    },
  ],

  'th-013': [
    {
      id: 'th-013-r1',
      threadId: 'th-013',
      postNumber: 2,
      body: '> forty minutes before the meeting\n\nI want to ask the technical question first. was the transcription running in the background or did it activate during this window. some apps have always-on modes that log locally even when the interface shows idle.',
      createdAt: '24 min ago',
      authorHandle: 'STATIC_VEIL',
      authorMode: 'ghost',
      reactions: r(8, 3, 5, 6, 1),
    },
    {
      id: 'th-013-r2',
      threadId: 'th-013',
      postNumber: 3,
      body: 'the more interesting problem is not the technical mechanism. it is the content. the folder with the red tab. that is a physical object. someone in that meeting knew about it at the time of the log. the transcription did not invent it.',
      createdAt: '19 min ago',
      authorHandle: 'SIGNAL_BLEED',
      authorMode: 'ghost',
      reactions: r(21, 7, 14, 17, 3),
    },
    {
      id: 'th-013-r3',
      threadId: 'th-013',
      postNumber: 4,
      body: 'had something adjacent happen. my note app created a new note containing the exact text of an email I received three hours later. the note timestamp is real. the email was from someone I had not spoken to in eight months.',
      createdAt: '14 min ago',
      authorHandle: 'ANON',
      authorMode: 'anon',
      reactions: r(28, 10, 19, 22, 5),
    },
    {
      id: 'th-013-r4',
      threadId: 'th-013',
      postNumber: 5,
      body: '> I have the raw file\n\nif you can share the hash without sharing the content, that would at least establish that the file was not modified after the fact. the metadata chain matters more than the content here.',
      createdAt: '8 min ago',
      authorHandle: 'ARCHIVE_SIFT',
      authorMode: 'ghost',
      reactions: r(14, 5, 9, 11, 2),
    },
  ],

  'th-015': [
    {
      id: 'th-015-r1',
      threadId: 'th-015',
      postNumber: 2,
      body: 'the correction memo is the important artifact. routine renaming does not generate a memo instructing removal from all future documentation. that language is active suppression, not administrative correction.',
      createdAt: '1 hour 45 min ago',
      authorHandle: 'ARCHIVE_SIFT',
      authorMode: 'ghost',
      reactions: r(18, 6, 12, 15, 3),
    },
    {
      id: 'th-015-r2',
      threadId: 'th-015',
      postNumber: 3,
      body: 'I found a third usage of the original name in a 1931 insurance document from an adjacent county. the coverage was for a structure that no longer appears on any post-1953 map of the area.',
      createdAt: '1 hour 22 min ago',
      authorHandle: 'LEDGER_NODE',
      authorMode: 'ghost',
      reactions: r(24, 8, 16, 19, 4),
    },
    {
      id: 'th-015-r3',
      threadId: 'th-015',
      postNumber: 4,
      body: 'what was in that neighborhood in the gap years. between the pre-gap name and the 1939 renaming. that window is what the memos are protecting.',
      createdAt: '58 min ago',
      authorHandle: 'NULL_RELAY',
      authorMode: 'ghost',
      reactions: r(19, 6, 13, 15, 3),
    },
    {
      id: 'th-015-r4',
      threadId: 'th-015',
      postNumber: 5,
      body: 'these memo patterns appear in at least seven other municipal archives I have researched. always the same structure: two memos, no reason given, same language about all future documentation. someone was writing from a template.',
      createdAt: '29 min ago',
      authorHandle: 'ANON',
      authorMode: 'anon',
      reactions: r(31, 10, 20, 24, 5),
    },
  ],

  'th-016': [
    {
      id: 'th-016-r1',
      threadId: 'th-016',
      postNumber: 2,
      body: '> all 14 report the flicker\n\nI want to flag the statistical problem here. fourteen independent witnesses with no prior discussion reaching the same description is not a confabulation pattern. confabulation clusters differently. this is corroboration.',
      createdAt: '41 min ago',
      authorHandle: 'SIGNAL_BLEED',
      authorMode: 'ghost',
      reactions: r(28, 9, 18, 22, 5),
    },
    {
      id: 'th-016-r2',
      threadId: 'th-016',
      postNumber: 3,
      body: 'the security footage gap is the detail that cannot be resolved technically. if the footage is complete with clean timecodes, it either recorded and shows no flicker — which means the witnesses are wrong — or something affected physical experience without affecting the recording medium.',
      createdAt: '37 min ago',
      authorHandle: 'GLITCH_DIET',
      authorMode: 'ghost',
      reactions: r(35, 12, 23, 28, 7),
    },
    {
      id: 'th-016-r3',
      threadId: 'th-016',
      postNumber: 4,
      body: '> 0.3 seconds\n\nall fourteen witnesses gave the same duration estimate independently. 0.3 seconds is below conscious threshold for most visual anomaly estimation. people usually overestimate short durations. fourteen people guessing the same precise duration is unusual.',
      createdAt: '30 min ago',
      authorHandle: 'FRAGMENT_08',
      authorMode: 'ghost',
      reactions: r(41, 14, 28, 34, 8),
    },
    {
      id: 'th-016-r4',
      threadId: 'th-016',
      postNumber: 5,
      body: 'I was in a building three years ago where everyone reported hearing a single tone simultaneously. no source was found. the building audio system was off. no one had a phone out. it lasted under one second. the description from all eight people was the same frequency estimate.',
      createdAt: '22 min ago',
      authorHandle: 'ANON',
      authorMode: 'anon',
      reactions: r(24, 8, 16, 19, 4),
    },
    {
      id: 'th-016-r5',
      threadId: 'th-016',
      postNumber: 6,
      body: '> the footage shows nothing\n\nI want to suggest the possibility that the footage is correct and the witnesses are correct. if the event affected biological perception but not electromagnetic recording, that tells you something about the mechanism.',
      createdAt: '12 min ago',
      authorHandle: 'NULL_RELAY',
      authorMode: 'ghost',
      reactions: r(52, 18, 36, 44, 11),
    },
  ],
};
