import type { DbScannerSource } from '@/lib/supabase/types';

/**
 * Seed registry of candidate scanner sources.
 *
 * STATUS: REGISTRY ONLY — no fetchers connected, no automated scanning.
 * All sources start enabled=false. A curator must manually enable each one
 * before any automated fetch pipeline could ever use it (future phase).
 *
 * Human approval is required at every stage. These entries document
 * WHERE signals could be recovered from — not that recovery is happening.
 */
export const SCANNER_SOURCES_SEED: DbScannerSource[] = [
  {
    id: 'src-001',
    name: 'Erowid Experience Vaults',
    source_type: 'archive',
    base_url: 'https://erowid.org/experiences/',
    description:
      'Community-submitted psychedelic and altered-state experience reports. Rich source of consciousness anomalies, entity encounters, machine elves, and DMT-space phenomena. Carefully moderated since 1995.',
    category_focus: ['Psychedelics', 'Consciousness', 'Paranormal', 'Spirituality'],
    risk_level: 'low',
    refresh_cadence: 'weekly',
    attribution_rules:
      'Credit "Erowid.org Experience Vaults" with original author handle if public. Summarize — do not reproduce full trip report text.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-002',
    name: 'Wayback Machine — Deleted Forums',
    source_type: 'archive',
    base_url: 'https://web.archive.org/',
    description:
      'Internet Archive snapshots of deleted paranormal forums, dead BBS boards, and vanished discussion threads. Primary recovery vector for signals that no longer exist at their original URLs.',
    category_focus: ['Paranormal', 'UFOs', 'Hidden History', 'Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Always link to the Wayback snapshot URL, not the original dead URL. Note original site name and approximate deletion date when known.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-003',
    name: 'AboveTopSecret Forums',
    source_type: 'forum',
    base_url: 'https://www.abovetopsecret.com/',
    description:
      'Long-running conspiracy and paranormal forum active since 2001. Decades of archived UFO sighting reports, government whistleblower claims, and anomaly threads. Some content removed over time — cross-reference Wayback for deleted posts.',
    category_focus: ['UFOs', 'Conspiracy Theory', 'Whistleblower Files', 'Paranormal', 'Shadow Systems'],
    risk_level: 'medium',
    refresh_cadence: 'weekly',
    attribution_rules:
      'Credit original poster handle and thread creation date. Do not reproduce long quote chains. Summarize the core claim only.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-004',
    name: 'r/Glitch_in_the_Matrix',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/Glitch_in_the_Matrix/',
    description:
      'Personal accounts of reality anomalies: deja vu loops, timeline inconsistencies, impossible coincidences, and simulation breaks. High signal density for consciousness and simulation anomaly categories.',
    category_focus: ['Simulation Theory', 'Paranormal', 'Weird Encounters', 'Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'daily',
    attribution_rules:
      'Credit u/[handle] on r/Glitch_in_the_Matrix with post date. Summarize — do not reproduce full post text. Link to archived version if available.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-005',
    name: 'Lost Media Wiki',
    source_type: 'mediawiki',
    base_url: 'https://www.lostmediawiki.com/',
    description:
      'Community-maintained encyclopedia of lost, destroyed, or buried media: missing TV episodes, unreleased films, deleted recordings, suppressed games. Strong source for media anomalies and cultural erasure signals.',
    category_focus: ['Lost Media', 'Internet Mysteries', 'Conspiracy Theory', 'Censored History'],
    risk_level: 'low',
    refresh_cadence: 'weekly',
    attribution_rules:
      'Credit "Lost Media Wiki" with article title and page URL. Note when recovery status changed (found / still lost).',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-006',
    name: 'Textfiles.com — BBS Archives',
    source_type: 'bbs',
    base_url: 'https://www.textfiles.com/',
    description:
      'Massive archive of 1980s–1990s BBS text files: early UFO reports, pre-internet conspiracy theories, occult texts, hacker manifestos, underground zines. Raw signal from before the web. Much is anonymous — no account names.',
    category_focus: ['UFOs', 'Paranormal', 'Conspiracy Theory', 'Occult Archives', 'Hidden History', 'Forbidden Tech'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit textfiles.com with the BBS name and subdirectory path. Note approximate year of the file. Most authors are anonymous by design.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-007',
    name: '/x/ Paranormal — 4plebs Archive',
    source_type: 'imageboard',
    base_url: 'https://archive.4plebs.org/x/',
    description:
      'Archived threads from 4chan /x/ paranormal board. High noise, occasional genuine signal. Focus on recurring thread archetypes: tulpa encounters, sigil work, entity contact, reality anomalies, and creepypasta with authentic texture.',
    category_focus: ['Paranormal', 'Occult Archives', 'Weird Encounters', 'Internet Lore', 'Internet Mysteries'],
    risk_level: 'high',
    refresh_cadence: 'manual',
    attribution_rules:
      'Anonymous by default — no personal attribution. Note board (/x/), thread ID, and archive date. Screen carefully for PII before intake.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-009',
    name: 'r/HighStrangeness',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/HighStrangeness/',
    description:
      'Curated accounts of high-strangeness phenomena: cryptids, UAPs, dimensional anomalies, telepathy, precognition, and unexplained encounters that resist simple explanation.',
    category_focus: ['Paranormal', 'UFOs', 'Weird Encounters', 'Consciousness'],
    risk_level: 'low',
    refresh_cadence: 'daily',
    attribution_rules:
      'Credit u/[handle] on r/HighStrangeness with post date. Summarize — do not reproduce full post.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-010',
    name: 'r/Paranormal',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/Paranormal/',
    description:
      'Personal paranormal experiences: ghost sightings, shadow figures, poltergeist activity, haunted locations, and unexplained phenomena shared by ordinary people.',
    category_focus: ['Paranormal', 'Weird Encounters', 'Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'daily',
    attribution_rules:
      'Credit u/[handle] on r/Paranormal with post date. Summarize — do not reproduce full post.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-011',
    name: 'r/LostMedia',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/lostmedia/',
    description:
      'Community searching for lost, forgotten, and unrecovered media: rare recordings, missing footage, suppressed broadcasts, and internet media that vanished.',
    category_focus: ['Lost Media', 'Internet Mysteries', 'Censored History'],
    risk_level: 'low',
    refresh_cadence: 'weekly',
    attribution_rules:
      'Credit u/[handle] on r/lostmedia with post date. Summarize — do not reproduce full post.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-012',
    name: 'r/UnresolvedMysteries',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/UnresolvedMysteries/',
    description:
      'In-depth discussions of unsolved disappearances, unexplained deaths, cold cases, and real-world mysteries that remain unresolved. High signal density for conspiracy and hidden history categories.',
    category_focus: ['Conspiracy Theory', 'Hidden History', 'Paranormal', 'Whistleblower Files'],
    risk_level: 'low',
    refresh_cadence: 'daily',
    attribution_rules:
      'Credit u/[handle] on r/UnresolvedMysteries with post date. Summarize — do not reproduce full post.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-013',
    name: 'r/LetsNotMeet',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/LetsNotMeet/',
    description:
      'True stories of terrifying real-world encounters with strangers, stalkers, and predators. First-person eyewitness accounts with high emotional intensity — strong narrative and unresolved-mystery signals.',
    category_focus: ['Paranormal', 'Weird Encounters', 'Hidden History'],
    risk_level: 'low',
    refresh_cadence: 'daily',
    attribution_rules:
      'Credit u/[handle] on r/LetsNotMeet with post date. Summarize — do not reproduce full post.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-014',
    name: 'r/RBI',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/RBI/',
    description:
      'Reddit Bureau of Investigation — community-driven mystery solving. Real unsolved cases, missing persons, strange discoveries, and internet mysteries submitted for collective investigation.',
    category_focus: ['Conspiracy Theory', 'Hidden History', 'Internet Mysteries', 'Paranormal'],
    risk_level: 'low',
    refresh_cadence: 'daily',
    attribution_rules:
      'Credit u/[handle] on r/RBI with post date. Summarize — do not reproduce full post.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-015',
    name: 'r/Retconned',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/Retconned/',
    description:
      'Mandela Effect and timeline anomalies — collective memories that differ from documented history. Personal accounts of reality inconsistencies, alternate timelines, and mass false memory events.',
    category_focus: ['Simulation Theory', 'Paranormal', 'Weird Encounters'],
    risk_level: 'low',
    refresh_cadence: 'daily',
    attribution_rules:
      'Credit u/[handle] on r/Retconned with post date. Summarize — do not reproduce full post.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-016',
    name: 'r/Thetruthishere',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/Thetruthishere/',
    description:
      'Personal paranormal experiences, encounters with the unexplained, and anomalous events that resist rational explanation. Eyewitness-focused with strong unresolved-mystery framing.',
    category_focus: ['Paranormal', 'Weird Encounters', 'UFOs'],
    risk_level: 'low',
    refresh_cadence: 'daily',
    attribution_rules:
      'Credit u/[handle] on r/Thetruthishere with post date. Summarize — do not reproduce full post.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-017',
    name: 'r/InternetMysteries',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/InternetMysteries/',
    description:
      'Unsolved internet mysteries, strange websites, cryptic ARGs, lost or unidentified online content, and digital anomalies. Strong signal source for internet lore and lost media categories.',
    category_focus: ['Internet Mysteries', 'Lost Media', 'Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'weekly',
    attribution_rules:
      'Credit u/[handle] on r/InternetMysteries with post date. Summarize — do not reproduce full post.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  // ── Phase J new sources ─────────────────────────────────────────────────
  {
    id: 'src-018',
    name: 'r/AskReddit',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/AskReddit/',
    description:
      'Anomaly-adjacent threads only — "have you ever experienced something you cannot explain", unexplained events, paranormal encounters asked to a mass audience. Requires strict keyword filtering; volume is enormous.',
    category_focus: ['Paranormal', 'Weird Encounters', 'Consciousness'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit u/[handle] on r/AskReddit with post date. Summarize top answers — do not reproduce full comment threads.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-019',
    name: 'r/creepyencounters',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/creepyencounters/',
    description:
      'First-person accounts of unexplained, disturbing real-world encounters. High narrative density — strong signal for weird encounters and eyewitness-testimony categories.',
    category_focus: ['Paranormal', 'Weird Encounters'],
    risk_level: 'low',
    refresh_cadence: 'daily',
    attribution_rules:
      'Credit u/[handle] on r/creepyencounters with post date. Summarize — do not reproduce full post.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-020',
    name: 'r/BackwoodsCreepy',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/BackwoodsCreepy/',
    description:
      'Strange and unsettling encounters in wilderness and rural settings: unexplained lights, missing persons mysteries, impossible sounds, and encounters in the deep woods.',
    category_focus: ['Paranormal', 'Weird Encounters', 'Hidden History'],
    risk_level: 'low',
    refresh_cadence: 'daily',
    attribution_rules:
      'Credit u/[handle] on r/BackwoodsCreepy with post date. Summarize — do not reproduce full post.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-021',
    name: 'r/Humanoidencounters',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/Humanoidencounters/',
    description:
      'Personal accounts of encounters with non-human humanoid entities — from Bigfoot-type cryptids to interdimensional beings and UAP-associated non-human intelligences.',
    category_focus: ['Paranormal', 'UFOs', 'Weird Encounters'],
    risk_level: 'low',
    refresh_cadence: 'daily',
    attribution_rules:
      'Credit u/[handle] on r/Humanoidencounters with post date. Summarize — do not reproduce full post.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-022',
    name: 'r/cryptids',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/cryptids/',
    description:
      'Discussion and sighting reports of cryptid creatures: Bigfoot, Dogman, Mothman, lake monsters, and other unclassified entities. Mix of eyewitness accounts and analysis.',
    category_focus: ['Paranormal', 'Weird Encounters'],
    risk_level: 'low',
    refresh_cadence: 'weekly',
    attribution_rules:
      'Credit u/[handle] on r/cryptids with post date. Summarize — do not reproduce full post.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-023',
    name: 'r/UFOs',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/UFOs/',
    description:
      'UAP sighting reports, government disclosure developments, FOIA releases, and whistleblower accounts. Active community with high-signal threads around congressional hearings and NHI claims.',
    category_focus: ['UFOs', 'Whistleblower Files', 'Government', 'Hidden History'],
    risk_level: 'low',
    refresh_cadence: 'daily',
    attribution_rules:
      'Credit u/[handle] on r/UFOs with post date. Summarize — do not reproduce full post.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-024',
    name: 'r/aliens',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/aliens/',
    description:
      'Discussion of extraterrestrial and NHI phenomena: abduction accounts, contact experiences, hybridization claims, and UAP/NHI intersection. Higher noise-to-signal ratio than r/UFOs.',
    category_focus: ['UFOs', 'Paranormal', 'Consciousness'],
    risk_level: 'low',
    refresh_cadence: 'weekly',
    attribution_rules:
      'Credit u/[handle] on r/aliens with post date. Summarize — do not reproduce full post.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-025',
    name: 'r/Dreams',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/Dreams/',
    description:
      'Shared dream experiences with unusual content: precognitive dreams, recurring archetypes, entity contact in dreams, and anomalous dream phenomena that resist conventional explanation.',
    category_focus: ['Consciousness', 'Paranormal', 'Spirituality'],
    risk_level: 'low',
    refresh_cadence: 'daily',
    attribution_rules:
      'Credit u/[handle] on r/Dreams with post date. Summarize — do not reproduce full post.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  // ── Phase O: Deep Archive / Origin Scan sources ────────────────────────
  {
    id: 'src-026',
    name: 'Wayback — GeoCities Archive',
    source_type: 'wayback',
    base_url: 'https://www.geocities.com/',
    description:
      'GeoCities was the defining 1990s personal web host — millions of pages about UFOs, paranormal, conspiracy theories, and weird phenomena from anonymous early adopters. Almost entirely deleted by Yahoo in 2009. Wayback CDX will find pre-2009 captures.',
    category_focus: ['Paranormal', 'UFOs', 'Internet Lore', 'Hidden History', 'Conspiracy Theory'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "GeoCities archive (pre-2009) via Wayback Machine". Note the original page owner handle or site name if visible. Era: 1990s–2000s web.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-027',
    name: 'Wayback — Angelfire Archive',
    source_type: 'wayback',
    base_url: 'https://www.angelfire.com/',
    description:
      'Angelfire hosted thousands of personal paranormal and UFO research pages through the late 1990s and 2000s. Strong source for grassroots conspiracy and encounter documentation before social media absorbed personal publishing.',
    category_focus: ['Paranormal', 'UFOs', 'Conspiracy Theory', 'Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "Angelfire archive (pre-2010) via Wayback Machine". Note original site title and author handle if visible.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-028',
    name: 'Wayback — Tripod Archive',
    source_type: 'wayback',
    base_url: 'https://www.tripod.lycos.com/',
    description:
      'Tripod (Lycos) was another major 1990s–2000s free web host with extensive paranormal, UFO, and alternative research content. Captures pre-2008 personal pages about phenomena that have since vanished from the open web.',
    category_focus: ['Paranormal', 'UFOs', 'Hidden History', 'Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "Tripod/Lycos archive (pre-2010) via Wayback Machine". Note original site title if visible.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-029',
    name: 'Wayback — AboveTopSecret Archive',
    source_type: 'wayback',
    base_url: 'https://www.abovetopsecret.com/',
    description:
      'AboveTopSecret forum threads from 2001–2012 before heavy moderation and content removal. Early UAP/disclosure speculation, government whistleblower claims, and first-generation conspiracy deep-dives that influenced later internet culture.',
    category_focus: ['UFOs', 'Conspiracy Theory', 'Whistleblower Files', 'Hidden History'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "AboveTopSecret archive via Wayback Machine · [year]". Note poster handle and original thread date.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-030',
    name: 'Wayback — Rense.com Archive',
    source_type: 'wayback',
    base_url: 'https://www.rense.com/',
    description:
      'Rense.com was one of the largest early alternative news aggregators (active since 1997), publishing UFO reports, suppressed science, government conspiracies, and anomalous phenomena. Pre-2010 captures document early internet paranoia culture.',
    category_focus: ['UFOs', 'Conspiracy Theory', 'Shadow Systems', 'Paranormal', 'Forbidden Tech'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "Rense.com archive via Wayback Machine · [year]". Treat claims as internet artifact — do not endorse. Note original publication date.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-031',
    name: 'Wayback — Bibliotecapleyades Archive',
    source_type: 'wayback',
    base_url: 'https://www.bibliotecapleyades.net/',
    description:
      'Spanish-origin alternative knowledge archive founded in 2000 — one of the most comprehensive collections of pre-social-media UFO, ancient history, and consciousness research articles. Extensively archived via Wayback.',
    category_focus: ['UFOs', 'Hidden History', 'Consciousness', 'Paranormal', 'Occult Archives'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "Bibliotecapleyades archive via Wayback Machine". Treat as research artifact. Cite original article title and author if visible.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-032',
    name: 'Wayback — Paranormal About.com Archive',
    source_type: 'wayback',
    base_url: 'https://paranormal.about.com/',
    description:
      'About.com\'s paranormal section was one of the web\'s most-visited paranormal reference hubs from the late 1990s through 2010. Covered ghosts, UFOs, cryptids, and unexplained phenomena with a mainstream editorial voice. Largely deleted in 2017.',
    category_focus: ['Paranormal', 'UFOs', 'Weird Encounters', 'Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "About.com Paranormal archive via Wayback Machine". Note article title, author, and approximate year.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-033',
    name: 'Wayback — Unexplained Mysteries Archive',
    source_type: 'wayback',
    base_url: 'https://www.unexplained-mysteries.com/',
    description:
      'Unexplained-Mysteries.com (est. 2001) was a major community hub for paranormal news, forum discussions, and case documentation. Pre-2010 forum threads capture early internet mystery discourse before Reddit dominated the space.',
    category_focus: ['Paranormal', 'UFOs', 'Internet Mysteries', 'Hidden History'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "Unexplained-Mysteries.com archive via Wayback Machine · [year]". Note original poster handle and thread date if visible.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-034',
    name: 'Textfiles.com — BBS Archives',
    source_type: 'bbs',
    base_url: 'https://www.textfiles.com/',
    description:
      'Jason Scott\'s textfiles.com preserves thousands of 1980s–1990s BBS text files: early UFO reports, pre-internet conspiracy theories, occult texts, encounter narratives, and hacker culture artifacts. Pure raw signal from before the web. Content is anonymous by design.',
    category_focus: ['UFOs', 'Paranormal', 'Conspiracy Theory', 'Occult Archives', 'Hidden History', 'Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit textfiles.com with BBS category path and filename. Note approximate decade. Authors are almost universally anonymous — do not fabricate attribution.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  // ── Phase V: Deep Origin Sources ────────────────────────────────────────
  {
    id: 'src-035',
    name: 'Crystalinks',
    source_type: 'archive',
    base_url: 'https://www.crystalinks.com/',
    description:
      'Ellie Crystal\'s Crystalinks (est. 1995) is one of the oldest continuously-running metaphysics and alternative history archives on the web. Covers ancient astronauts, sacred geometry, consciousness, paranormal phenomena, and interdimensional theory with an encyclopedic depth unusual for the 1990s web.',
    category_focus: ['Ancient History', 'Consciousness', 'UFOs', 'Occult Archives', 'Hidden History'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit "Crystalinks.com" with article title and URL. Note original publication year when visible. Content is personal research — treat as internet artifact.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-036',
    name: 'The Black Vault',
    source_type: 'archive',
    base_url: 'https://www.theblackvault.com/',
    description:
      'John Greenewald Jr.\'s Black Vault (est. 1996) hosts tens of thousands of government FOIA documents on UFOs, classified programs, and black projects — including declassified CIA, NSA, DIA, and DoD files. One of the most comprehensive public repositories of government UFO documentation.',
    category_focus: ['UFOs', 'Government', 'Whistleblower Files', 'Shadow Systems', 'Conspiracy Theory'],
    risk_level: 'low',
    refresh_cadence: 'weekly',
    attribution_rules:
      'Credit "The Black Vault" with document title and FOIA case number if available. Link to specific document page. Note the releasing agency and date of declassification.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-037',
    name: 'NICAP.org — UAP Case Files',
    source_type: 'archive',
    base_url: 'https://www.nicap.org/',
    description:
      'NICAP (National Investigations Committee on Aerial Phenomena, est. 1956) documented hundreds of UAP cases through the Cold War era. The nicap.org archive preserves pre-disclosure UAP case files, witness testimonies, and analysis from the 1950s–1970s — a primary source for historical UAP research.',
    category_focus: ['UFOs', 'Hidden History', 'Government', 'Whistleblower Files'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit "NICAP.org Case Files" with case ID and date. Treat as historical primary source — note the era (Cold War UAP documentation).',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-038',
    name: 'Internet Archive — UFO/Paranormal Text Collections',
    source_type: 'archive',
    base_url: 'https://archive.org/search?query=ufo+paranormal&mediatype=texts',
    description:
      'Internet Archive hosts thousands of digitized UFO, paranormal, and conspiracy research texts — including out-of-print books, self-published research, government hearings transcripts, and rare zines from the 1950s through 2000s. Free full-text search across public domain and openly licensed material.',
    category_focus: ['UFOs', 'Paranormal', 'Conspiracy Theory', 'Hidden History', 'Occult Archives'],
    risk_level: 'low',
    refresh_cadence: 'weekly',
    attribution_rules:
      'Credit "Internet Archive" with item title, author, and publication year. Note original publisher and archive upload date. Link to archive.org item page.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-039',
    name: 'Wayback — FortuneCity Archive',
    source_type: 'wayback',
    base_url: 'https://www.fortunecity.com/',
    description:
      'FortuneCity was a major free web host from 1997–2008 with substantial paranormal, UFO, and conspiracy content from the early internet era. Distinct from GeoCities — FortuneCity had a more international user base and different community norms. Almost entirely gone now. Wayback CDX will recover pre-2008 captures.',
    category_focus: ['Paranormal', 'UFOs', 'Internet Lore', 'Conspiracy Theory'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "FortuneCity archive (pre-2008) via Wayback Machine". Note original page owner handle or site name if visible.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-040',
    name: 'Wayback — Project Camelot Archive',
    source_type: 'wayback',
    base_url: 'https://projectcamelot.org/',
    description:
      'Project Camelot (est. 2006) conducted video interviews with whistleblowers, insiders, and researchers on classified programs, UFO cover-ups, and black projects. Pre-2012 Wayback captures document the early interview archive before the site evolved. Treat as archived claim — claims are unverified.',
    category_focus: ['UFOs', 'Whistleblower Files', 'Shadow Systems', 'Conspiracy Theory'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "Project Camelot archive via Wayback Machine · [year]". Note: all claims are unverified and should be framed as archived whistleblower testimony — not established fact.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-041',
    name: 'Wayback — Project Avalon Archive',
    source_type: 'wayback',
    base_url: 'https://projectavalon.net/',
    description:
      'Project Avalon (est. 2009, spin-off from Project Camelot) hosted whistleblower interviews and a large community forum discussing classified programs, exopolitics, and financial systems. The pre-2013 forum archive contains early crowdsourced investigation threads. Claims are unverified.',
    category_focus: ['UFOs', 'Whistleblower Files', 'Conspiracy Theory', 'Shadow Systems'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "Project Avalon archive via Wayback Machine · [year]". Frame as internet artifact / archived claim. Verify before treating as factual.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-042',
    name: 'Wayback — Nexus Magazine Archive',
    source_type: 'wayback',
    base_url: 'https://www.nexusmagazine.com/',
    description:
      'Nexus Magazine (est. 1987, Australian) covers suppressed science, alternative health, UFOs, and conspiracy research — one of the longest-running independent alt-research publications. Pre-2010 Wayback captures include article indexes from the 1990s print era that were digitized online.',
    category_focus: ['UFOs', 'Forbidden Tech', 'Conspiracy Theory', 'Hidden History', 'Paranormal'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "Nexus Magazine archive via Wayback Machine · [year]". Note volume/issue number if visible. Treat claims as archived research artifact.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-043',
    name: 'Wayback — Earthfiles.com Archive',
    source_type: 'wayback',
    base_url: 'https://www.earthfiles.com/',
    description:
      'Linda Moulton Howe\'s Earthfiles.com (est. 1999) covered UAPs, animal mutilations, crop circles, and anomalous environmental phenomena with journalist rigor. Pre-2010 reports document field investigations and witness interviews before much of the archive moved behind a paywall.',
    category_focus: ['UFOs', 'Paranormal', 'Weird Encounters', 'Hidden History'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "Earthfiles.com archive via Wayback Machine · [year]". Credit Linda Moulton Howe as author/investigator. Note original report date.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-044',
    name: 'Wayback — CUFON Computer UFO Network',
    source_type: 'wayback',
    base_url: 'https://www.cufon.org/',
    description:
      'CUFON (Computer UFO Network, est. 1988) was one of the first computer-based UFO research networks — predating the web. The cufon.org site archived declassified documents, case files, and early computer network UFO bulletins from the late 1980s through 1990s. Rare pre-web digital UFO research.',
    category_focus: ['UFOs', 'Government', 'Hidden History', 'Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "CUFON archive via Wayback Machine · [year]". Note document type (government file, case report, BBS bulletin). Era: 1988–late 1990s digital UFO research.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-045',
    name: 'Wayback — UFO Updates Mailing List',
    source_type: 'wayback',
    base_url: 'https://www.virtuallystrange.net/ufo/updates/',
    description:
      'UFO UpDates was the premier email discussion list for serious UFO researchers from 1996–2010, moderated by Errol Bruce-Knapp. The Virtuallystrange.net archive preserves thousands of researcher exchanges with Stanton Friedman, Bruce Maccabee, Nick Pope, and others — a primary source for 1990s UFO discourse.',
    category_focus: ['UFOs', 'Hidden History', 'Whistleblower Files', 'Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "UFO UpDates mailing list archive via Wayback Machine · [year]". Credit researcher name and original post date when visible.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-046',
    name: 'Wayback — EZBoard Paranormal Forums',
    source_type: 'wayback',
    base_url: 'https://pub.ezboard.com/',
    description:
      'EZBoard (later Yuku) hosted thousands of independent paranormal, UFO, and conspiracy forums through the late 1990s and 2000s — many have been deleted. Wayback CDX captures pre-2010 forum threads with community discussion of phenomena that predate Reddit. High signal density for origin-era internet discourse.',
    category_focus: ['Paranormal', 'UFOs', 'Conspiracy Theory', 'Internet Lore', 'Weird Encounters'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "EZBoard forum archive via Wayback Machine · [year]". Note forum name and thread title. Authors are typically pseudonymous handles.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-047',
    name: 'Wayback — ParaScope Archive',
    source_type: 'wayback',
    base_url: 'https://www.parascope.com/',
    description:
      'ParaScope (est. 1995) was one of the earliest web-based UFO and conspiracy research hubs — active during the X-Files cultural moment. It hosted original investigations, government document analyses, and community features before disappearing in the early 2000s. Rare window into 1990s web conspiracy culture.',
    category_focus: ['UFOs', 'Conspiracy Theory', 'Internet Lore', 'Hidden History'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "ParaScope archive via Wayback Machine · [year]". Era: 1995–2002 early web UFO research. Authors are named in original articles where visible.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-048',
    name: 'Wayback — The Anomalist Archive',
    source_type: 'wayback',
    base_url: 'https://www.anomalist.com/',
    description:
      'The Anomalist (est. 1995) is a daily newsfeed covering Fortean topics — UAPs, cryptids, anomalous phenomena, and fringe science — with a scholarly skeptical lens. Pre-2010 Wayback captures preserve years of linked article archives that catalogued anomaly research before modern aggregators.',
    category_focus: ['Paranormal', 'UFOs', 'Weird Encounters', 'Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "The Anomalist archive via Wayback Machine · [year]". Note original linked source and date.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-049',
    name: 'Wayback — ForteanTimes.com Archive',
    source_type: 'wayback',
    base_url: 'https://www.forteantimes.com/',
    description:
      'Fortean Times (UK, est. 1973 in print, online since 1997) documents strange phenomena, anomalous events, and Fortean curiosities — the academic journal of the weird. Pre-2012 web archive captures contain case files, investigative articles, and research by serious anomaly researchers.',
    category_focus: ['Paranormal', 'UFOs', 'Weird Encounters', 'Hidden History', 'Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "Fortean Times archive via Wayback Machine · [year]". Note article title and author. Era: 1997–2012 web archive of UK anomaly journalism.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-050',
    name: 'Wayback — Stanton Friedman Archives',
    source_type: 'wayback',
    base_url: 'https://www.stantonfriedman.com/',
    description:
      'Nuclear physicist and UFO researcher Stanton Friedman\'s personal website (1990s–2019) hosted declassified documents, research papers, and case analyses — particularly on Roswell and Majestic-12. Friedman died in 2019; his archive is one of the most credentialed primary-source UFO research collections online.',
    category_focus: ['UFOs', 'Whistleblower Files', 'Government', 'Hidden History'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "Stanton Friedman archive via Wayback Machine · [year]". Credit Stanton T. Friedman as author/researcher. Note document type.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-051',
    name: 'Wayback — MUFON.com Archive',
    source_type: 'wayback',
    base_url: 'https://www.mufon.com/',
    description:
      'MUFON (Mutual UFO Network, est. 1969) is one of the oldest civilian UAP investigation organizations. Pre-2010 web archive captures preserve case investigation reports, field investigator analyses, and MUFON Journal content from before the organization\'s modern database migration.',
    category_focus: ['UFOs', 'Paranormal', 'Whistleblower Files', 'Hidden History'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "MUFON archive via Wayback Machine · [year]". Note case number, investigator, and incident date where available.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-052',
    name: 'Wayback — alt.ufo / alt.paranormal Usenet Mirror',
    source_type: 'wayback',
    base_url: 'https://groups.google.com/g/alt.ufo/',
    description:
      'Google Groups preserves Usenet newsgroup archives including alt.ufo, alt.paranormal, alt.alien.visitors, and alt.conspiracy from the early 1990s. These newsgroups predate the web and contain the earliest internet-native discussion of UFOs and paranormal phenomena. Wayback captures recover deleted threads.',
    category_focus: ['UFOs', 'Paranormal', 'Conspiracy Theory', 'Internet Lore', 'Hidden History'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "Usenet archive via Google Groups · [newsgroup] · [year]". Note poster handle and date. Authors are typically pseudonymous.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-053',
    name: 'Wayback — Coast to Coast AM Early Archive',
    source_type: 'wayback',
    base_url: 'https://www.coasttocoastam.com/',
    description:
      'Coast to Coast AM (est. 1984 with Art Bell) is the premier overnight radio show for paranormal, UFO, and conspiracy discussions. Pre-2010 web archive captures document show summaries, guest transcripts, and Art Bell-era interviews that are no longer accessible on the current site.',
    category_focus: ['Paranormal', 'UFOs', 'Conspiracy Theory', 'Weird Encounters'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "Coast to Coast AM archive via Wayback Machine · [year]". Note host (Art Bell / George Noory) and guest name. Era: 1998–2010 web archive.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-054',
    name: 'Wayback — NUFORC Early Reports',
    source_type: 'wayback',
    base_url: 'https://www.nuforc.org/',
    description:
      'NUFORC (National UFO Reporting Center, est. 1974) maintains one of the oldest databases of civilian UAP sighting reports in the US. Pre-2005 Wayback captures preserve original report formats and early database structures before multiple site migrations that obscured early data.',
    category_focus: ['UFOs', 'Paranormal', 'Hidden History'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules:
      'Credit as "NUFORC sighting report via Wayback Machine · [year]". Note report date, location, and report ID if visible.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  // ── Group B: Sacred Texts / Occult Archives ─────────────────────────────
  {
    id: 'src-055',
    name: 'Sacred-Texts.com — Occult & Esoteric Library',
    source_type: 'archive',
    base_url: 'https://www.sacred-texts.com/',
    description: 'One of the oldest free online archives of religious, occult, and esoteric texts — Kabbalah, Hermeticism, Theosophist writings, UFO contactee accounts, and early 20th century occultism. Operating since 1999 with over 1,000 documents.',
    category_focus: ['Occult Archives', 'Hidden History', 'Consciousness', 'Spirituality'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit "Sacred-Texts.com" with text title and author. Note original publication date/era. Summarize — do not reproduce wholesale.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-056',
    name: 'Hermetic.com — Western Hermetic Library',
    source_type: 'archive',
    base_url: 'https://hermetic.com/',
    description: 'Digital library of Western esotericism: Crowley texts, Golden Dawn rituals, OTO documents, Thelema, and ceremonial magic. Also hosts alt.magick Usenet archives from the 1990s–2000s internet occult scene.',
    category_focus: ['Occult Archives', 'Hidden History', 'Consciousness'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit "Hermetic.com" with text title and author. Most works are public domain or author-released.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-057',
    name: 'Wayback — Cassiopaea.org Transcripts',
    source_type: 'wayback',
    base_url: 'https://www.cassiopaea.org/',
    description: 'Cassiopaea.org archives Laura Knight-Jadczyk\'s channeling session transcripts from 1994 onward — alleged contact communications covering UFOs, historical revisionism, and hyperdimensional theory. Pre-2010 Wayback captures preserve original session transcripts before site restructuring.',
    category_focus: ['UFOs', 'Occult Archives', 'Consciousness', 'Paranormal'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "Cassiopaea.org transcript via Wayback Machine · [year]". Frame as archived channeling artifact — claims are metaphysical and unverifiable.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-058',
    name: 'Wayback — Crystalinks Early Archive (pre-2005)',
    source_type: 'wayback',
    base_url: 'https://www.crystalinks.com/',
    description: 'Early Wayback captures (1999–2005) of Crystalinks before major site restructuring — preserves the original 1990s metaphysics encyclopedia layout. Complements the live site (src-035) with earlier, less-curated material.',
    category_focus: ['Ancient History', 'Consciousness', 'UFOs', 'Occult Archives'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "Crystalinks.com archive (pre-2005) via Wayback Machine". Note article title and original page date.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  // ── Group C: Conspiracy / Alt-Knowledge Archives ─────────────────────────
  {
    id: 'src-059',
    name: 'Bibliotecapleyades.net — Live Archive',
    source_type: 'archive',
    base_url: 'https://www.bibliotecapleyades.net/',
    description: 'Live access to Bibliotecapleyades (est. 2000) — one of the most comprehensive Spanish-origin alternative knowledge archives on the web. Over 300 subject categories covering UFOs, ancient history, consciousness research, and exopolitics. The Wayback version (src-031) captures older snapshots.',
    category_focus: ['UFOs', 'Hidden History', 'Consciousness', 'Paranormal', 'Occult Archives', 'Conspiracy Theory'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit "Bibliotecapleyades.net" with article title and author. Treat as alternative research archive — not verified fact.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-060',
    name: 'Rex Research — Fringe Science Repository',
    source_type: 'archive',
    base_url: 'https://www.rexresearch.com/',
    description: 'Rex Research (est. 1982 in print, online since 1997) archives suppressed and fringe science: free energy devices, zero-point energy, orgone research, anti-gravity experiments. Raw primary documentation of non-mainstream technical claims — patents, inventor correspondence, research notes.',
    category_focus: ['Forbidden Tech', 'Conspiracy Theory', 'Hidden History'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit "Rex Research" with inventor/researcher name and technology name. Frame as fringe science archive — claims unverified.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-061',
    name: 'KeelyNet — Alternative Science Archive',
    source_type: 'archive',
    base_url: 'https://www.keelynet.com/',
    description: 'KeelyNet (Jerry Decker, est. 1988 on BBS) is one of the original alt-science BBS networks, now a web archive. Covers free energy, anti-gravity, Tesla research, electrogravity, and fringe physics claims from 1988 through the 2010s. Invaluable primary source for pre-web fringe science discourse.',
    category_focus: ['Forbidden Tech', 'Hidden History', 'Conspiracy Theory'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit "KeelyNet" with researcher name and date. Frame as fringe science archive — claims are speculative.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-062',
    name: 'Wayback — Surfing the Apocalypse Archive',
    source_type: 'wayback',
    base_url: 'https://www.surfingtheapocalypse.net/',
    description: 'Surfing the Apocalypse (est. late 1990s) was a major early alternative news site covering UFO disclosure, government conspiracies, earth changes, and suppressed science. Pre-2010 captures preserve thousands of archived posts from the early web conspiracy ecosystem.',
    category_focus: ['UFOs', 'Conspiracy Theory', 'Shadow Systems', 'Hidden History'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "Surfing the Apocalypse archive via Wayback Machine · [year]". Frame as archived internet conspiracy artifact — claims unverified.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-063',
    name: 'Wayback — AlienShift Archive',
    source_type: 'wayback',
    base_url: 'https://www.alienshift.com/',
    description: 'AlienShift (late 1990s–2000s) hosted research on ET contact, ancient astronauts, and interdimensional theory — part of the early web\'s "exopolitics before exopolitics" scene. Wayback captures preserve content from before the domain changed hands.',
    category_focus: ['UFOs', 'Ancient History', 'Consciousness', 'Paranormal'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "AlienShift archive via Wayback Machine · [year]". Early-web internet artifact — claims unverified.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-064',
    name: 'Wayback — Educate-Yourself.org Archive',
    source_type: 'wayback',
    base_url: 'https://educate-yourself.org/',
    description: 'Educate-Yourself.org (Ken Adachi, est. 1998) covered chemtrails, mind control programs, free energy suppression, and NWO claims. Pre-2010 captures document early internet conspiracy discourse. High misinformation risk — use only for archival/historical analysis of the conspiracy narrative ecosystem.',
    category_focus: ['Conspiracy Theory', 'Shadow Systems', 'Forbidden Tech'],
    risk_level: 'high',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "Educate-Yourself.org archive via Wayback Machine · [year]". INTERNET ARTIFACT ONLY — some claims are demonstrably false. Frame as historical conspiracy artifact.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-065',
    name: 'Wayback — StopTheCrime.net Archive',
    source_type: 'wayback',
    base_url: 'https://stopthecrime.net/',
    description: 'StopTheCrime.net covered Agenda 21, geoengineering, frequency weapons, and global surveillance claims from the 2010s. Wayback captures preserve the site before multiple takedowns. High misinformation risk — for archival analysis of contemporary conspiracy discourse only.',
    category_focus: ['Conspiracy Theory', 'Shadow Systems'],
    risk_level: 'high',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "StopTheCrime.net archive via Wayback Machine · [year]". INTERNET ARTIFACT ONLY — claims unverified. Historical framing only.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  // ── Group D: Fringe Science / Free Energy ───────────────────────────────
  {
    id: 'src-066',
    name: 'Wayback — Tom Bearden Energy Archive',
    source_type: 'wayback',
    base_url: 'https://www.cheniere.org/',
    description: 'Lt. Col. Tom Bearden\'s cheniere.org hosted his scalar electromagnetics and zero-point energy theory work — extensively cited in fringe physics circles through the 1990s–2010s. Pre-2012 Wayback captures document the full published archive.',
    category_focus: ['Forbidden Tech', 'Hidden History'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "Tom Bearden / cheniere.org archive via Wayback Machine · [year]". Fringe physics archive — claims outside mainstream science.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-067',
    name: 'Wayback — PureEnergySystems Archive',
    source_type: 'wayback',
    base_url: 'https://www.pureenergysystems.com/',
    description: 'PureEnergySystems.com / Open Source Energy Network (Sterling Allan, est. 2003) catalogued hundreds of claimed free energy and over-unity devices with inventor profiles and test results. A primary index of early-2000s alt-energy claims. Pre-2014 captures.',
    category_focus: ['Forbidden Tech', 'Hidden History', 'Conspiracy Theory'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "PureEnergySystems.com archive via Wayback Machine · [year]". Fringe energy research catalog — devices described are unverified.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  // ── Group E: Old-Web Wayback Targets ────────────────────────────────────
  {
    id: 'src-068',
    name: 'Wayback — Homestead.com Archive',
    source_type: 'wayback',
    base_url: 'https://www.homestead.com/',
    description: 'Homestead.com was a major 1990s–2000s free web host used extensively for personal UFO, paranormal, and conspiracy pages. Pre-2010 Wayback captures recover personal research sites that have since disappeared.',
    category_focus: ['Paranormal', 'UFOs', 'Internet Lore', 'Conspiracy Theory'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "Homestead.com archive (pre-2010) via Wayback Machine". Note original page owner or site title if visible.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-069',
    name: 'Wayback — Xoom.com Archive',
    source_type: 'wayback',
    base_url: 'https://www.xoom.com/',
    description: 'Xoom (later acquired by NBCi) was a 1990s free web host popular for early personal paranormal and alternative research pages before GeoCities dominated. Pre-2002 captures are rare windows into the very first wave of web-native paranormal content.',
    category_focus: ['Paranormal', 'UFOs', 'Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "Xoom.com archive (pre-2002) via Wayback Machine". Note original page owner if visible. Era: 1996–2001 early web.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-070',
    name: 'Wayback — Brinkster.com Archive',
    source_type: 'wayback',
    base_url: 'https://www.brinkster.com/',
    description: 'Brinkster was a free web hosting service used by personal sites in the late 1990s and early 2000s. Home to numerous paranormal, UFO, and conspiracy research pages that have since disappeared. Underexplored Wayback target for early-web content.',
    category_focus: ['Paranormal', 'UFOs', 'Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "Brinkster.com archive (pre-2005) via Wayback Machine". Note original site name or author if visible.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  // ── Group F: Forum Archives ──────────────────────────────────────────────
  {
    id: 'src-071',
    name: 'Wayback — GodLike Productions Forum Archive',
    source_type: 'archive_forum',
    base_url: 'https://www.godlikeproductions.com/',
    description: 'Archived GLP forum threads from the 2000s–2012 via Wayback — distinct from the live GLP site (src-008). Early GLP was a signal-rich forum for emerging conspiracy narratives, UAP speculation, and whistleblower posts before heavy moderation. GLP blocks direct linking; Wayback is the only accessible archive.',
    category_focus: ['UFOs', 'Conspiracy Theory', 'Paranormal', 'Whistleblower Files'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "GodLike Productions forum archive via Wayback Machine · [year]". Poster handles only. Frame as early-internet forum artifact.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-072',
    name: 'Wayback — Lunatic Outpost Forum Archive',
    source_type: 'archive_forum',
    base_url: 'https://www.lunaticoutpost.com/',
    description: 'Lunatic Outpost was a mid-2000s conspiracy and paranormal forum with deep-dives into black programs, breakaway civilization theory, and UAP phenomena. Pre-2013 Wayback captures preserve the early forum before significant content loss.',
    category_focus: ['UFOs', 'Conspiracy Theory', 'Shadow Systems', 'Paranormal'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "Lunatic Outpost forum archive via Wayback Machine · [year]". Poster handles only. Frame as archived internet conspiracy artifact.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-073',
    name: 'Wayback — Armageddon Online Forum Archive',
    source_type: 'archive_forum',
    base_url: 'https://www.armageddononline.org/',
    description: 'Armageddon Online was an early-2000s doomsday and earth-change forum hosting discussion of hidden earth history and government foreknowledge of disasters. Pre-2010 Wayback threads document the disaster/hidden-history genre of early internet paranoia.',
    category_focus: ['Hidden History', 'Conspiracy Theory', 'Paranormal'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "Armageddon Online forum archive via Wayback Machine · [year]". Claims unverified — archived internet content.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-074',
    name: 'Wayback — Unexplained-Mysteries Forum Archive',
    source_type: 'archive_forum',
    base_url: 'https://www.unexplained-mysteries.com/forum/',
    description: 'The Unexplained-Mysteries.com forum (2001–present) was an early community for paranormal discussion. Wayback captures of pre-2010 threads preserve early-era discourse before later moderation changes. Targets the forum subdirectory specifically — see src-033 for the main site.',
    category_focus: ['Paranormal', 'UFOs', 'Internet Lore', 'Weird Encounters'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "Unexplained-Mysteries forum archive via Wayback Machine · [year]". Note poster handle and thread date.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  // ── Group G: Internet Archive Collections ────────────────────────────────
  {
    id: 'src-075',
    name: 'Internet Archive — MUFON Journal Back Issues',
    source_type: 'archive',
    base_url: 'https://archive.org/search?query=MUFON+journal&mediatype=texts',
    description: 'Digitized back issues of the MUFON UFO Journal (est. 1967) — original case investigation reports, field investigator analyses, and researcher correspondence from the 1960s through 2000s. Primary source for civilian UAP investigation history.',
    category_focus: ['UFOs', 'Hidden History', 'Whistleblower Files'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit "MUFON UFO Journal" with volume, issue number, and article author. Civilian investigation organization — frame claims accordingly.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-076',
    name: 'Internet Archive — UFO Congressional Hearings',
    source_type: 'archive',
    base_url: 'https://archive.org/search?query=UFO+congressional+hearing&mediatype=texts',
    description: 'Digitized transcripts of US congressional hearings on UFOs/UAPs — from the 1960s Robertson Panel era through modern AARO oversight. Includes Project Blue Book final report, COMETA Report, and official government UAP assessment documents.',
    category_focus: ['UFOs', 'Government', 'Whistleblower Files', 'Hidden History'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit "US Congressional Record" or specific hearing title with date. Official government documents — cite formally.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-077',
    name: 'Internet Archive — Ancient Mysteries & Alternative History',
    source_type: 'archive',
    base_url: 'https://archive.org/search?query=ancient+mysteries+alternative+history&mediatype=texts',
    description: 'Thousands of digitized books, zines, and research papers on alternative archaeology, lost civilizations, ancient astronauts, and suppressed prehistory. Spans 1950s through 2000s print-era alternative history research.',
    category_focus: ['Ancient History', 'Hidden History', 'UFOs', 'Occult Archives'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit Internet Archive with book/document title, author, and publisher. Note publication date. Treat as research archive, not established academic history.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-078',
    name: 'Internet Archive — Art Bell / Coast to Coast Audio',
    source_type: 'archive',
    base_url: 'https://archive.org/search?query=art+bell+coast+to+coast&mediatype=audio',
    description: 'Community-uploaded Art Bell Coast to Coast AM recordings — thousands of hours from the mid-1990s through mid-2000s peak era. Contains the original interviews with whistleblowers, abductees, and researchers that defined the genre. Audio-only; requires transcript/summary for text extraction.',
    category_focus: ['Paranormal', 'UFOs', 'Conspiracy Theory', 'Weird Encounters'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit "Art Bell / Coast to Coast AM" with show date and guest name. Audio clips are fan uploads — use for summary/reference only.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-079',
    name: 'Internet Archive — Pre-Internet UFO Newsletters',
    source_type: 'archive',
    base_url: 'https://archive.org/search?query=UFO+newsletter+bulletin&mediatype=texts',
    description: 'Digitized pre-web UFO research newsletters from the 1950s–1990s: APRO Bulletin, CUFOS IUR, Flying Saucer Review, and dozens of regional UFO group publications. Primary sources for the civilian UFO research movement before the internet era.',
    category_focus: ['UFOs', 'Hidden History', 'Whistleblower Files'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit newsletter title, volume/issue, and original publication date. Historical primary sources for UFO research history.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-080',
    name: 'Internet Archive — Conspiracy Research Texts',
    source_type: 'archive',
    base_url: 'https://archive.org/search?query=conspiracy+research&mediatype=texts',
    description: 'Broad collection of digitized conspiracy research books and samizdat from the 1970s–2000s: JFK assassination research, mind control programs, black budget exposés, and shadow government documentation. Wide net — requires careful curation.',
    category_focus: ['Conspiracy Theory', 'Shadow Systems', 'Government', 'Hidden History'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit Internet Archive with document title, author, and original publication date. Wide quality variance — treat as research artifact.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  // ── Group H: UFO Databases ───────────────────────────────────────────────
  {
    id: 'src-081',
    name: 'UFO Evidence.org — Case Database',
    source_type: 'archive',
    base_url: 'https://www.ufoevidence.org/',
    description: 'UFO Evidence (est. 2001) provides a structured database of UAP cases with evidence quality ratings, witness categories, and cross-references to official investigations. Focused on physical evidence cases, radar contacts, and multiple-witness events.',
    category_focus: ['UFOs', 'Hidden History', 'Government', 'Whistleblower Files'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit "UFO Evidence.org" with case ID and date. Note evidence quality rating and original investigation source.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-082',
    name: 'Wayback — Majestic Documents Archive',
    source_type: 'wayback',
    base_url: 'https://www.majesticdocuments.com/',
    description: 'MajesticDocuments.com (Ryan Wood) archives alleged MJ-12 and Majestic documents — contested government documents relating to early UFO recovery programs. The authenticity debate itself is historically significant. Pre-2015 captures preserve the full document archive and analysis.',
    category_focus: ['UFOs', 'Government', 'Whistleblower Files', 'Conspiracy Theory'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "Majestic Documents archive via Wayback Machine · [year]". CONTESTED AUTHENTICITY — frame as alleged documents; authenticity disputed.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-083',
    name: 'UFO Casebook — Sighting Reports',
    source_type: 'archive',
    base_url: 'https://www.ufocasebook.com/',
    description: 'UFO Casebook (est. 1999) maintains an extensive database of documented UAP sightings with photographs, radar data, and investigator analysis. Hundreds of well-documented classic cases from the 1940s through present. Strong for historical sighting reports with physical evidence.',
    category_focus: ['UFOs', 'Paranormal', 'Hidden History'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit "UFO Casebook" with case title and date. Note reporting investigator and evidence type.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-084',
    name: 'Open Minds UFO — Research Archive',
    source_type: 'archive',
    base_url: 'https://www.openminds.tv/',
    description: 'Open Minds Production (est. 2008) produced investigative journalism on UAPs: original reporting, researcher interviews, and case analysis. The news archive covers 2008–2020 UAP developments with journalistic rigor atypical for the field.',
    category_focus: ['UFOs', 'Whistleblower Files', 'Government'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit "Open Minds UFO" with article title, author, and publication date.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-085',
    name: 'Wayback — UFO Digest Archive',
    source_type: 'wayback',
    base_url: 'https://www.ufodigest.com/',
    description: 'UFO Digest (est. 2004) was a major UFO news aggregator publishing original articles, witness reports, and researcher profiles through the mid-2010s. Pre-2015 Wayback captures preserve the original article archive before content loss.',
    category_focus: ['UFOs', 'Paranormal', 'Conspiracy Theory'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "UFO Digest archive via Wayback Machine · [year]". Note article author and date. Quality varies — treat as internet artifact.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  // ── Group I: Fiction / Lore Layer ────────────────────────────────────────
  {
    id: 'src-086',
    name: 'SCP Foundation Wiki',
    source_type: 'mediawiki',
    base_url: 'https://scp-wiki.wikidot.com/',
    description: 'The SCP Foundation collaborative fiction wiki — thousands of entries documenting fictional anomalous objects, entities, and phenomena in a classified-document style. Extremely high-quality worldbuilding. Fiction layer only. Enable only for lore/fiction research, never as a factual signal source.',
    category_focus: ['Internet Lore', 'Paranormal'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'FICTION — Credit "SCP Foundation Wiki" with SCP number and title. Always frame as collaborative fiction. Do not present as factual accounts.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-087',
    name: 'Creepypasta Wiki',
    source_type: 'mediawiki',
    base_url: 'https://creepypasta.fandom.com/',
    description: 'The Creepypasta Wiki hosts collaborative horror fiction from internet culture: Jeff the Killer, Slenderman, Smile Dog, and thousands of original horror stories. Primary source for internet horror lore. Fiction only — enable only for narrative/lore analysis.',
    category_focus: ['Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'FICTION — Credit "Creepypasta Wiki" with story title and author. Always frame as fictional internet horror narrative. Never present as factual.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-088',
    name: 'The Backrooms Wiki',
    source_type: 'mediawiki',
    base_url: 'https://backrooms.fandom.com/',
    description: 'The Backrooms collaborative fiction wiki documenting the liminal space mythology originating from a 2019 4chan post. Expanded into thousands of "levels" with detailed lore. Fiction layer — useful for internet mythology research only.',
    category_focus: ['Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'FICTION — Credit "The Backrooms Wiki" with level/entry title. Always frame as collaborative internet fiction. Lore layer source only.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-089',
    name: 'r/NoSleep',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/nosleep/',
    description: 'Horror fiction subreddit where posts are presented as true first-person accounts by convention. Very high-quality horror writing with verisimilitude — but ALL content is fictional. Disabled by default to prevent fiction contamination of factual signal pools.',
    category_focus: ['Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'FICTION BY CONVENTION — Credit u/[handle] on r/nosleep. Frame explicitly as horror fiction. The sub requires treating posts as true, but SWIM must flag as fiction.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-090',
    name: 'r/ARG',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/ARG/',
    description: 'r/ARG community tracks ongoing and completed Alternate Reality Games and internet rabbit holes. Useful for distinguishing genuine internet mysteries from manufactured ARGs. Enable for internet-mystery and lore research.',
    category_focus: ['Internet Mysteries', 'Internet Lore'],
    risk_level: 'low',
    refresh_cadence: 'weekly',
    attribution_rules: 'Credit u/[handle] on r/ARG with post date. Note whether ARG is ongoing, solved, or unsolved. Flag as possible fiction when status is unclear.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-091',
    name: 'Wayback — Unfiction Forum Archive',
    source_type: 'wayback',
    base_url: 'https://www.unfiction.com/',
    description: 'Unfiction (est. 2002, now defunct) was the primary community for tracking ARGs — including I Love Bees, Majestic, and Year Zero. Pre-2010 forum archive preserves the original collaborative puzzle-solving threads that defined the ARG genre and internet mystery culture.',
    category_focus: ['Internet Lore', 'Internet Mysteries'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "Unfiction forum archive via Wayback Machine · [year]". Note ARG title and resolution status. Game-related content — not real phenomena.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  // ── Group J: Document Archives / Discovery Hubs ──────────────────────────
  {
    id: 'src-092',
    name: 'CIA CREST — UFO & Paranormal Files',
    source_type: 'archive',
    base_url: 'https://www.cia.gov/readingroom/collection/ufos-fact-or-fiction',
    description: 'The CIA\'s official CREST Reading Room hosts declassified UFO-related files — 1952 Robertson Panel documents, Project Blue Book coordination, and STARGATE psychic research materials. Primary government source for declassified UAP documentation.',
    category_focus: ['UFOs', 'Government', 'Whistleblower Files', 'Shadow Systems'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit "CIA CREST Reading Room" with document title, date, and document number. Official declassified government documents — cite formally.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-093',
    name: 'NSA.gov — Declassified UFO Documents',
    source_type: 'archive',
    base_url: 'https://www.nsa.gov/Helpful-Links/NSA-FOIA/Frequently-Requested-Records/UFO/',
    description: 'NSA\'s official FOIA release of UFO-related documents — signals intelligence reports, communications intercepts, and internal memos related to UAP phenomena from the Cold War era. Among the most credentialed primary sources for SIGINT perspectives on UAPs.',
    category_focus: ['UFOs', 'Government', 'Whistleblower Files'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit "NSA FOIA Release" with document title and declassification date. Official government documents — cite formally with document number if available.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-094',
    name: 'Cryptome.org — Leaked Government Documents',
    source_type: 'archive',
    base_url: 'https://cryptome.org/',
    description: 'Cryptome (John Young, est. 1996) publishes leaked and FOIA-released government documents on surveillance, intelligence operations, nuclear facilities, and classified programs. Not UFO-specific — covers state secrecy broadly. High signal for shadow systems but requires careful legal/ethical vetting.',
    category_focus: ['Shadow Systems', 'Government', 'Whistleblower Files', 'Conspiracy Theory'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit "Cryptome.org" with document title and date posted. Note whether alleged leak or official FOIA release. Do not reproduce documents in full.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-095',
    name: 'Wayback — UFO Roundup Newsletter',
    source_type: 'wayback',
    base_url: 'https://www.ufoinfo.com/roundup/',
    description: 'UFO Roundup was a weekly e-newsletter (Joseph Trainor, 1996–2009) aggregating global UAP sighting reports, cattle mutilation cases, and anomalous phenomena. Pre-2010 captures preserve over a decade of weekly global sighting compilations — a primary pre-social UAP news source.',
    category_focus: ['UFOs', 'Paranormal', 'Hidden History'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit "UFO Roundup" with volume, issue, and original correspondent/location where visible. Era: 1996–2009 pre-social UFO news.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-096',
    name: 'FOIA.gov — Declassified Records Search',
    source_type: 'archive',
    base_url: 'https://www.foia.gov/',
    description: 'FOIA.gov is the official US government FOIA portal aggregating declassified records across agencies. Discovery hub for tracking newly declassified materials related to UAPs, classified programs, and government research. Requires specific queries — not a direct bulk content source.',
    category_focus: ['Government', 'UFOs', 'Shadow Systems', 'Whistleblower Files'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit the specific releasing agency with FOIA case number and document date. Official government records.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-097',
    name: 'Wayback — Hyper.net Conspiracy Archive',
    source_type: 'wayback',
    base_url: 'https://www.hyper.net/',
    description: 'Hyper.net hosted one of the earliest comprehensive web conspiracy archives in the mid-1990s — covering JFK, MK-ULTRA, Roswell, and secret societies before most of the internet existed. Pre-2002 Wayback captures are extremely rare windows into the very first wave of web-native conspiracy research.',
    category_focus: ['Conspiracy Theory', 'UFOs', 'Shadow Systems', 'Internet Lore'],
    risk_level: 'medium',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "Hyper.net conspiracy archive via Wayback Machine · [year]". Era: 1994–2001 earliest web conspiracy archive.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-098',
    name: 'Wayback — UFO Evidence Early Archive',
    source_type: 'wayback',
    base_url: 'https://www.ufoevidence.org/',
    description: 'Early Wayback captures (2001–2008) of UFO Evidence before multiple database migrations. The original site format preserved case reports in a different structure than the current live site (src-081). Complements live access with cases that may have been removed in later editions.',
    category_focus: ['UFOs', 'Hidden History', 'Government'],
    risk_level: 'low',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit as "UFO Evidence archive via Wayback Machine · [year]". Note case ID and original report date.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  // ── Additional Reddit Communities ────────────────────────────────────────
  {
    id: 'src-099',
    name: 'r/Experiencers',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/Experiencers/',
    description: 'First-person accounts from individuals claiming ongoing contact with non-human intelligences — abductees, contactees, and CE-5 practitioners. Higher narrative density for direct-contact accounts than r/UFOs. Strong for consciousness and direct-contact categories.',
    category_focus: ['UFOs', 'Consciousness', 'Paranormal', 'Weird Encounters'],
    risk_level: 'low',
    refresh_cadence: 'weekly',
    attribution_rules: 'Credit u/[handle] on r/Experiencers with post date. First-person accounts — summarize sensitively. Do not reproduce full text.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-100',
    name: 'r/GhostStories',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/GhostStories/',
    description: 'First-person ghost sighting and haunting experiences with stricter posting rules requiring personal account format. Higher signal quality than r/Paranormal for hauntings, apparitions, and unexplained entity phenomena.',
    category_focus: ['Paranormal', 'Weird Encounters'],
    risk_level: 'low',
    refresh_cadence: 'weekly',
    attribution_rules: 'Credit u/[handle] on r/GhostStories with post date. Summarize — do not reproduce full post.',
    enabled: true,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-101',
    name: 'r/conspiracy',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/conspiracy/',
    description: 'Large general conspiracy theory subreddit. Extremely high noise-to-signal ratio — politically volatile, mixes real anomaly discourse with misinformation and disinfo. Disabled by default. Enable only with tight keyword filtering and heavy curation oversight.',
    category_focus: ['Conspiracy Theory', 'Shadow Systems', 'Government'],
    risk_level: 'high',
    refresh_cadence: 'manual',
    attribution_rules: 'Credit u/[handle] on r/conspiracy with post date. Frame as community conspiracy speculation — not verified claims. Heavy curation required before any publication.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'src-102',
    name: 'r/StrangeEarth',
    source_type: 'reddit',
    base_url: 'https://www.reddit.com/r/StrangeEarth/',
    description: 'Reports of bizarre natural phenomena, geological anomalies, strange sounds (sky trumpets, the hum), unusual animal behavior, and unexplained environmental events. Crossover source between paranormal and fringe science categories.',
    category_focus: ['Paranormal', 'Weird Encounters', 'Hidden History'],
    risk_level: 'low',
    refresh_cadence: 'weekly',
    attribution_rules: 'Credit u/[handle] on r/StrangeEarth with post date. Summarize — do not reproduce full post.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  // ── Legacy / high-risk sources ──────────────────────────────────────────
  {
    id: 'src-008',
    name: 'GodLike Productions',
    source_type: 'forum',
    base_url: 'https://www.godlikeproductions.com/',
    description:
      'High-volume conspiracy and paranormal forum known for early reports on emerging phenomena before mainstream coverage. Mixed signal quality — requires heavy curation. GLP blocks external referrers, so links must go to Wayback snapshots.',
    category_focus: ['UFOs', 'Paranormal', 'Conspiracy Theory', 'Government', 'Whistleblower Files'],
    risk_level: 'high',
    refresh_cadence: 'manual',
    attribution_rules:
      'Summarize only. Do not link directly to GLP — they block external referrers. Always use Wayback snapshot URL. Verify post dates carefully.',
    enabled: false,
    last_scanned_at: null,
    created_at: '2024-01-01T00:00:00Z',
  },
];
