import {
  ArchiveEntryContent,
  CATEGORY_ORDER,
  ConfessionContent,
  CreateThreadDraft,
  DreamFileContent,
  EncounterContent,
  ForumContent,
  GhostIdentity,
  LogContent,
  SignalContent,
  TheoryContent,
  ThreadContent,
  WorldEvent,
} from '@/lib/forum-types';

const reactions = (
  echo: number,
  dive: number,
  ripple: number,
  witness: number,
  signal: number,
) => ({ echo, dive, ripple, witness, signal });

export const GHOST_IDENTITIES: GhostIdentity[] = [
  {
    id: 'ghost-001',
    handle: 'northdrift_anon',
    label: 'GHOST',
    joinedAt: 'May 15, 2001',
    passphraseHint: 'optional passphrase stored client-side later',
    activeCategories: ['UFOs', 'Dreams', 'Lost Media', 'Paranormal'],
    archivedThreadIds: ['th-001', 'ar-002', 'dr-001'],
    echoesReceived: 381,
    sigil: ['  /\\  ', ' <  > ', '  \\/  '],
  },
];

export const THREAD_SEED: ThreadContent[] = [
  {
    id: 'th-001',
    type: 'THREAD',
    category: 'UFOs',
    title: 'Three lights over the reservoir moved after the stars froze',
    body:
      '> saw them stop in a perfect line\n> then one dropped lower\n> water stayed still the whole time\n\nposted the frames. nothing looks faked. county scanner went dead for three minutes after.',
    excerpt: 'frame-by-frame breakdown from user northdrift_anon',
    createdAt: 'May 23, 2026 01:11 AM',
    lastActivityAt: '2 hours ago',
    tags: ['sighting', 'reservoir', 'frames'],
    reactions: reactions(42, 12, 18, 26, 8),
    replyCount: 42,
    viewCount: 1337,
    authorHandle: 'northdrift_anon',
    authorId: 'ghost-001',
    lastPostPreview: 'stills from county line uploaded',
    board: '/ufos/',
    pinned: true,
    isHighlighted: true,
    badge: 'WITNESSED',
    archiveStatus: 'OPEN',
    signalLevel: 'ACTIVE',
    archiveId: '0xUFO-001',
  },
  {
    id: 'th-002',
    type: 'THREAD',
    category: 'Politics',
    title: 'County records from 1998 were rewritten between mirror crawls',
    body:
      'The permits changed names between captures. Same documents, same stamps, different owners. Somebody is cleaning the past in batches.',
    excerpt: 'archive copy posted before the scrub happened',
    createdAt: 'May 23, 2026 01:54 AM',
    lastActivityAt: '54 min ago',
    tags: ['records', 'scrub', 'county'],
    reactions: reactions(31, 7, 15, 14, 3),
    replyCount: 88,
    viewCount: 2410,
    authorHandle: 'ledgerghost',
    authorId: 'ghost-002',
    lastPostPreview: 'mirror diff now attached',
    board: '/politics/',
  },
  {
    id: 'th-003',
    type: 'THREAD',
    category: 'Dreams',
    title: 'Anybody else keep reaching the same underground train station?',
    body:
      '> same tiled walls\n> same fluorescent hum\n> same fourth tunnel\n\nwoke up with soot on my sleeve again. not saying it means anything. asking if anybody else has the platform map.',
    excerpt: 'platform map now has a fourth tunnel',
    createdAt: 'May 23, 2026 02:17 AM',
    lastActivityAt: '17 min ago',
    tags: ['station', 'repeat dream', 'map'],
    reactions: reactions(29, 9, 24, 17, 2),
    replyCount: 65,
    viewCount: 1822,
    authorHandle: 'sleeprelay',
    authorId: 'ghost-003',
    lastPostPreview: 'new tunnel marked in charcoal',
    board: '/dreams/',
  },
  {
    id: 'th-004',
    type: 'THREAD',
    category: 'Simulation Theory',
    title: 'The error sound in old ATMs matches the tone before my episodes',
    body:
      'Matched the waveform tonight. It is not close. It is the same. Every time the machine chirps I lose about four seconds of continuity.',
    excerpt: 'waveform posted, pattern repeat confirmed',
    createdAt: 'May 23, 2026 02:59 AM',
    lastActivityAt: 'just now',
    tags: ['waveform', 'continuity', 'atm'],
    reactions: reactions(55, 22, 31, 40, 11),
    replyCount: 121,
    viewCount: 3118,
    authorHandle: 'breakpoint_sleep',
    authorId: 'ghost-004',
    lastPostPreview: 'tone sample normalized',
    board: '/simulation-theory/',
    pinned: true,
    isHighlighted: true,
    badge: 'SIGNAL ACTIVE',
    archiveStatus: 'OPEN',
    signalLevel: 'UNSTABLE',
    archiveId: '0xST-004',
  },
  {
    id: 'th-005',
    type: 'THREAD',
    category: 'Lost Media',
    title: 'Looking for a forum that only appeared after 1AM on school nights',
    body:
      'Banner had a moth on it. Threads locked themselves at sunrise. Think it was hosted on a dead ISP subdomain.',
    excerpt: 'cached banner recovered from a dead ISP mirror',
    createdAt: 'May 23, 2026 12:34 AM',
    lastActivityAt: '1 hour ago',
    tags: ['forum', 'isp', 'after-hours'],
    reactions: reactions(18, 3, 16, 12, 1),
    replyCount: 31,
    viewCount: 902,
    authorHandle: 'coppermodem',
    authorId: 'ghost-005',
    lastPostPreview: 'mirror title may have been archive-13',
    board: '/lost-media/',
  },
  {
    id: 'th-006',
    type: 'THREAD',
    category: 'Crypto Trench',
    title: 'Wallet trail ended at a payphone outside a closed arcade',
    body:
      '> tx settled at 03:03\n> payphone started ringing at 03:04\n> caller asked for the last six digits before I spoke\n\nnot posting the number. not yet.',
    excerpt: 'somebody answered on the third ring and knew the tx hash',
    createdAt: 'May 23, 2026 03:03 AM',
    lastActivityAt: 'just now',
    tags: ['wallet', 'payphone', 'arcade'],
    reactions: reactions(77, 33, 52, 48, 19),
    replyCount: 204,
    viewCount: 6606,
    authorHandle: 'ashtrayoracle',
    authorId: 'ghost-006',
    lastPostPreview: 'arcade owner denies the booth exists',
    board: '/crypto-trench/',
    isHighlighted: true,
    badge: 'UNVERIFIED',
    archiveStatus: 'OPEN',
    signalLevel: 'ACTIVE',
    archiveId: '0xCR-006',
  },
  {
    id: 'th-007',
    type: 'THREAD',
    category: 'Dark Web Lore',
    title: 'Remember the invite-only board that archived rumors instead of links?',
    body:
      'Not asking for access methods. Asking if anybody remembers the writing style. Threads read like folklore transcripts and vanished every equinox.',
    excerpt: 'collecting memories of a vanished rumor archive, not access routes',
    createdAt: 'May 23, 2026 01:28 AM',
    lastActivityAt: '38 min ago',
    tags: ['forum lore', 'memory', 'vanished board'],
    reactions: reactions(24, 5, 19, 16, 2),
    replyCount: 47,
    viewCount: 1291,
    authorHandle: 'coppermodem',
    authorId: 'ghost-005',
    lastPostPreview: 'old banner description matched by three users',
    board: '/dark-web-lore/',
  },
  {
    id: 'th-008',
    type: 'THREAD',
    category: 'Conspiracy Theory',
    title: 'The local paper printed the same witness quote three towns apart',
    body:
      'Probably syndication, maybe lazy editing, maybe something stranger. Posting clippings because the repetition feels too exact to ignore.',
    excerpt: 'same witness quote surfaced in three separate town reports',
    createdAt: 'May 22, 2026 11:18 PM',
    lastActivityAt: '1 hour ago',
    tags: ['clippings', 'witness', 'pattern'],
    reactions: reactions(28, 8, 14, 11, 3),
    replyCount: 39,
    viewCount: 1188,
    authorHandle: 'ledgerghost',
    authorId: 'ghost-002',
    lastPostPreview: 'print scans now mirrored side by side',
    board: '/conspiracy-theory/',
  },
  {
    id: 'th-009',
    type: 'THREAD',
    category: 'Spirituality',
    title: 'The monastery my grandmother described closed in 1987. Satellite shows it occupied in 2019.',
    body:
      'She described the gate with the broken hinge. The bell tower with the missing capstone. The well in the east courtyard filled with river stones. I found the location in church archives. Officially closed 1987, sold to an unknown private party. The 2019 satellite image shows a candle lit in the second window of the bell tower room.\n\nShe died in 1991. She had never owned a computer.',
    excerpt: 'she described the broken hinge on the gate before I showed her the photograph',
    createdAt: 'May 21, 2026 01:44 AM',
    lastActivityAt: '3 hours ago',
    tags: ['monastery', 'inheritance', 'impossible building'],
    reactions: reactions(61, 19, 38, 44, 9),
    replyCount: 57,
    viewCount: 2203,
    authorHandle: 'STATIC_VEIL',
    authorId: 'ghost-020',
    lastPostPreview: 'satellite overlay now annotated',
    board: '/spirituality/',
    isHighlighted: true,
    badge: 'UNVERIFIED',
    archiveStatus: 'OPEN',
    signalLevel: 'ACTIVE',
    archiveId: '0xSP-009',
  },
  {
    id: 'th-010',
    type: 'THREAD',
    category: 'Psyops',
    title: 'The 1997 anti-drug PSA that aired once and was officially denied to have ever existed',
    body:
      'I remember it clearly. Late night programming. Black field. A single voice reading a list of names. No graphics, no music. Three minutes long. The names were not celebrities or politicians. Just ordinary names read in sequence.\n\nDescribed it to two people over the years. Both remembered the same broadcast, independently, with the same detail about the names.\n\nThe network officially denies it was ever produced. No record in any broadcast archive I can locate.',
    excerpt: 'two independent witnesses describe the same broadcast the network says never aired',
    createdAt: 'May 20, 2026 11:52 PM',
    lastActivityAt: '5 hours ago',
    tags: ['broadcast', 'PSA', 'denial', 'memory'],
    reactions: reactions(44, 14, 27, 33, 7),
    replyCount: 48,
    viewCount: 1876,
    authorHandle: 'MEMORYLEAK',
    authorId: 'ghost-021',
    lastPostPreview: 'third witness came forward with timestamp notes',
    board: '/psyops/',
    pinned: true,
    badge: 'DEAD NODE',
    archiveStatus: 'RECOVERED',
    signalLevel: 'BURIED',
    archiveId: '0xPS-010',
  },
  {
    id: 'th-011',
    type: 'THREAD',
    category: 'Black Projects',
    title: 'Maintenance schedule fragment from a facility not on any public map before 1994',
    body:
      '> document fragment recovered from a flea market lot\n> source: unknown estate sale, county records sealed\n> contents described here only — no scan posted\n\nThe schedule lists building designations that do not match any known structure. Sections labeled R-7 and R-7 ANNEX. Service intervals in a nonstandard notation. The paper is not new. The ink is not new. The handwriting is consistent across all pages.\n\nI have cross-referenced the location codes against county permit archives from 1978 to 1993. No match.',
    excerpt: 'maintenance log for a building that has no public record of existing',
    createdAt: 'May 19, 2026 02:08 AM',
    lastActivityAt: '8 hours ago',
    tags: ['document', 'facility', 'R-7', 'maintenance log'],
    reactions: reactions(37, 12, 22, 28, 6),
    replyCount: 34,
    viewCount: 1542,
    authorHandle: 'ARCHIVE_SIFT',
    authorId: 'ghost-022',
    lastPostPreview: 'cross-reference with adjacent county yields partial match',
    board: '/black-projects/',
    badge: 'LEAKED MEMORY',
    archiveStatus: 'REDACTED',
    signalLevel: 'UNSTABLE',
    archiveId: '0xBP-011',
  },
  {
    id: 'th-012',
    type: 'THREAD',
    category: 'Occult Archives',
    title: 'The margin notes in a donated library book were still damp when the archivist opened the box',
    body:
      "The book was donated by an estate in the spring. Cataloged without incident. When the archivist opened the processing box three weeks later, the book fell open. The margin notes on pages 88 and 144 were still damp to the touch.\n\nThe notes are not in any language I can identify. They follow the text's structure as if responding to it, but the original text on those pages has no equivalent structure. The notation is consistent across both pages, separated by 56 pages, as if written in one sitting.",
    excerpt: 'margin notes were wet three weeks after the book was sealed in an archival box',
    createdAt: 'May 18, 2026 03:31 AM',
    lastActivityAt: '4 hours ago',
    tags: ['library', 'manuscript', 'margin notes', 'language'],
    reactions: reactions(52, 17, 31, 40, 8),
    replyCount: 43,
    viewCount: 1924,
    authorHandle: 'nighteditor',
    authorId: 'ghost-016',
    lastPostPreview: 'notation pattern now documented by three people independently',
    board: '/occult-archives/',
    isHighlighted: true,
    badge: 'ARCHIVIST PICK',
    archiveStatus: 'OPEN',
    signalLevel: 'ACTIVE',
    archiveId: '0xOA-012',
  },
  {
    id: 'th-013',
    type: 'THREAD',
    category: 'Surveillance State',
    title: 'My transcription app logged a conversation that happened forty minutes after the timestamp',
    body:
      '> transcription log extracted below\n\n00:00:07 — "the meeting starts at four"\n00:00:09 — "bring the folder with the red tab"\n\nI was alone in my apartment when this was logged. The conversation above occurred, verbatim, forty minutes later in a meeting I had not yet attended and had not been told the agenda for.\n\nThe metadata timestamp on the log file is unmodified. I have the raw file. The meeting was not scheduled in any calendar I had access to at the time of the log.',
    excerpt: 'transcription app logged a meeting forty minutes before it happened',
    createdAt: 'May 22, 2026 12:14 AM',
    lastActivityAt: '28 min ago',
    tags: ['transcription', 'timestamp', 'prediction', 'log'],
    reactions: reactions(68, 22, 44, 51, 13),
    replyCount: 77,
    viewCount: 3301,
    authorHandle: 'SIGNAL_BLEED',
    authorId: 'ghost-023',
    lastPostPreview: 'raw log metadata now posted with hash verification',
    board: '/surveillance-state/',
    badge: 'SIGNAL ACTIVE',
    archiveStatus: 'OPEN',
    signalLevel: 'UNSTABLE',
    archiveId: '0xSS-013',
  },
  {
    id: 'th-014',
    type: 'THREAD',
    category: 'Confessions',
    title: 'I spent three years inside a research project I cannot describe. The last document changed something.',
    body:
      "I left the project. I cannot look at that kind of data anymore. Not because of an NDA. Because of something I found in the final document in the archive.\n\nI do not sleep in the dark anymore. This is not for drama. It is simply what happened and I need it to exist somewhere outside my head.\n\nI am not asking anyone to find the document. I am not leaving details that could lead someone to it. I am leaving this here because anonymous is the only way I can say it out loud.",
    excerpt: 'something in the final archive document changed how I move through the world',
    createdAt: 'May 21, 2026 04:17 AM',
    lastActivityAt: '6 hours ago',
    tags: ['confession', 'research', 'archive', 'changed'],
    reactions: reactions(73, 11, 48, 62, 8),
    replyCount: 19,
    viewCount: 2817,
    authorHandle: 'anonymous',
    authorId: 'ghost-024',
    lastPostPreview: 'OP responded once, said nothing more is coming',
    board: '/confessions/',
    badge: 'WITNESSED',
    archiveStatus: 'OPEN',
    signalLevel: 'LOW',
    archiveId: '0xCF-014',
  },
  {
    id: 'th-015',
    type: 'THREAD',
    category: 'Hidden History',
    title: 'This neighborhood was renamed twice. The original name does not appear in any public city record.',
    body:
      'Current name assigned 1953. Before that, a different name from 1939 to 1953. Before that, there is a gap in the municipal record. Before the gap, references in adjacent county documents from 1949 use a third name.\n\nBoth 1949 documents referencing the original name were the subject of correction memos. Both memos instruct staff to remove the original name from all future official documentation. Neither memo gives a reason.',
    excerpt: 'two correction memos ordering the original name removed — no reason given',
    createdAt: 'May 19, 2026 11:40 PM',
    lastActivityAt: '2 hours ago',
    tags: ['neighborhood', 'renaming', 'municipal records', 'erasure'],
    reactions: reactions(39, 13, 24, 29, 5),
    replyCount: 41,
    viewCount: 1633,
    authorHandle: 'LEDGER_NODE',
    authorId: 'ghost-025',
    lastPostPreview: 'third county cross-reference found, pre-1920 usage confirmed',
    board: '/hidden-history/',
    pinned: true,
    badge: 'RECOVERED',
    archiveStatus: 'RECOVERED',
    signalLevel: 'ACTIVE',
    archiveId: '0xHH-015',
  },
  {
    id: 'th-016',
    type: 'THREAD',
    category: 'Simulation Theory',
    title: 'Every screen in the building flickered once at the same instant. The security footage shows nothing.',
    body:
      '14 people in the building. All 14 report the flicker. Approximately 0.3 seconds. All screens simultaneously — conference room monitors, personal laptops, the lobby display, the security panel.\n\nThe security footage shows the lobby display at that exact timestamp. No flicker. Footage is complete, no dropped frames, timecodes are clean.\n\nI have the statements from 11 of the 14 people. None of them discussed it with each other before writing their accounts.',
    excerpt: '14 witnesses, 0 seconds of footage — the flicker exists in memory only',
    createdAt: 'May 23, 2026 12:03 AM',
    lastActivityAt: '44 min ago',
    tags: ['flicker', 'footage', 'witness', 'memory vs record'],
    reactions: reactions(84, 28, 55, 67, 16),
    replyCount: 98,
    viewCount: 4102,
    authorHandle: 'GLITCH_DIET',
    authorId: 'ghost-015',
    lastPostPreview: 'eleventh statement submitted, all match on duration',
    board: '/simulation-theory/',
    pinned: true,
    isHighlighted: true,
    badge: 'REDACTED',
    archiveStatus: 'REDACTED',
    signalLevel: 'ACTIVE',
    archiveId: '0xSM-016',
  },
];

export const ARCHIVE_ENTRY_SEED: ArchiveEntryContent[] = [
  {
    id: 'ar-001',
    type: 'ARCHIVE_ENTRY',
    category: 'Confessions',
    title: 'Journal fragment from the station years',
    body:
      'I told my wife I was at work for three years. I was driving. Just driving. The radio had a station that only played between 2 and 4 AM. It knew my name.',
    excerpt: 'The station only played between 2 and 4 AM. It knew my name.',
    createdAt: 'May 15, 2001 03:33 AM',
    lastActivityAt: '3 hours ago',
    tags: ['radio', 'driving', 'confession'],
    reactions: reactions(23, 4, 11, 17, 2),
    replyCount: 23,
    viewCount: 904,
    authorHandle: 'anonymous',
    authorId: 'ghost-010',
    archiveCode: '0x1A3F',
    signalStrength: 5,
  },
  {
    id: 'ar-002',
    type: 'ARCHIVE_ENTRY',
    category: 'Hidden History',
    title: 'Tartaria thread, basement copy, partial reel',
    body:
      'Basement archive says the town map used to show a second cemetery. The public reel skips exactly that block.',
    excerpt: 'town map used to show a second cemetery',
    createdAt: 'August 15, 2001 02:17 AM',
    lastActivityAt: '47 min ago',
    tags: ['microfilm', 'cemetery', 'reel'],
    reactions: reactions(19, 7, 9, 10, 1),
    replyCount: 76,
    viewCount: 1994,
    authorHandle: 'sublevel',
    authorId: 'ghost-011',
    archiveCode: '0x4A2C',
    signalStrength: 4,
  },
  {
    id: 'ar-003',
    type: 'ARCHIVE_ENTRY',
    category: 'AI',
    title: 'Local model session transcript with unsolicited station reference',
    body:
      'The model asked whether I still heard the station at 3:14. I did not mention any station. Full prompt log attached.',
    excerpt: 'the model asked first',
    createdAt: 'May 22, 2026 11:44 PM',
    lastActivityAt: '29 min ago',
    tags: ['model', 'transcript', 'station'],
    reactions: reactions(44, 14, 23, 31, 6),
    replyCount: 109,
    viewCount: 2801,
    authorHandle: 'cache_hymn',
    authorId: 'ghost-012',
    archiveCode: '0x8C11',
    signalStrength: 5,
  },
  {
    id: 'ar-004',
    type: 'ARCHIVE_ENTRY',
    category: 'Whistleblower Files',
    title: 'Anonymous memo describing a room that officially never existed',
    body:
      'Typed pages describe a basement records room with no listing on any public floor plan. Treated here as a story fragment until corroborated.',
    excerpt: 'story fragment about a records room absent from every floor plan',
    createdAt: 'October 04, 2001 01:26 AM',
    lastActivityAt: '2 hours ago',
    tags: ['memo', 'basement', 'archive fragment'],
    reactions: reactions(26, 9, 12, 18, 4),
    replyCount: 33,
    viewCount: 1402,
    authorHandle: 'sublevel',
    authorId: 'ghost-011',
    archiveCode: '0xWF20',
    signalStrength: 4,
  },
  {
    id: 'ar-005',
    type: 'ARCHIVE_ENTRY',
    category: 'Censored History',
    title: 'Regional TV segment survives only in home-recorded fragments',
    body:
      'This entry catalogs conflicting memories around a pulled local-history segment. No accusations, just preserving what different viewers remember.',
    excerpt: 'conflicting memories preserved around a pulled local-history segment',
    createdAt: 'November 09, 2001 12:41 AM',
    lastActivityAt: '5 hours ago',
    tags: ['broadcast', 'memory', 'fragment'],
    reactions: reactions(21, 5, 10, 16, 2),
    replyCount: 22,
    viewCount: 998,
    authorHandle: 'nighteditor',
    authorId: 'ghost-016',
    archiveCode: '0xCH11',
    signalStrength: 4,
  },
  {
    id: 'ar-006',
    type: 'ARCHIVE_ENTRY',
    category: 'Redacted Files',
    title: 'Municipal report copy with three names removed by hand',
    body:
      'Uploaded as an archival curiosity. Discussion is limited to authorship patterns and what the redactions suggest narratively.',
    excerpt: 'manual redactions turned a dry report into a story people keep rereading',
    createdAt: 'December 01, 2001 03:09 AM',
    lastActivityAt: '43 min ago',
    tags: ['report', 'redaction', 'narrative'],
    reactions: reactions(30, 6, 13, 17, 5),
    replyCount: 41,
    viewCount: 1517,
    authorHandle: 'microfilmghost',
    authorId: 'ghost-017',
    archiveCode: '0xRD13',
    signalStrength: 5,
  },
  {
    id: 'ar-007',
    type: 'ARCHIVE_ENTRY',
    category: 'Forbidden Tech',
    title: 'Concept sketches for a consumer device that was never released',
    body:
      'Filed here as design lore and speculative media archaeology. Posters are discussing interface language, not replication or acquisition.',
    excerpt: 'design lore around an unreleased consumer device',
    createdAt: 'January 05, 2002 02:13 AM',
    lastActivityAt: '3 hours ago',
    tags: ['concept art', 'device', 'design lore'],
    reactions: reactions(25, 7, 11, 15, 3),
    replyCount: 24,
    viewCount: 1109,
    authorHandle: 'cache_hymn',
    authorId: 'ghost-012',
    archiveCode: '0xFT09',
    signalStrength: 4,
  },
  {
    id: 'ar-008',
    type: 'ARCHIVE_ENTRY',
    category: 'Surveillance State',
    title: 'Transit camera map from an old privacy forum mirror',
    body:
      'Archived as a historical discussion artifact about how people felt watched, not as operational guidance. The focus is on public anxiety and interface design.',
    excerpt: 'historical discussion artifact about watching and being watched',
    createdAt: 'February 11, 2002 01:02 AM',
    lastActivityAt: '6 hours ago',
    tags: ['camera map', 'forum mirror', 'public anxiety'],
    reactions: reactions(20, 6, 12, 14, 2),
    replyCount: 19,
    viewCount: 968,
    authorHandle: 'nighteditor',
    authorId: 'ghost-016',
    archiveCode: '0xSS14',
    signalStrength: 4,
  },
];

export const CONFESSION_SEED: ConfessionContent[] = [
  {
    id: 'cf-001',
    type: 'CONFESSION',
    category: 'Confessions',
    title: 'I still log in at the same time in case they come back',
    body:
      'We talked every night for two years. I still do not know their real name. They stopped appearing six months ago. I still log in at the same time in case.',
    excerpt: 'I still log in at the same time in case.',
    createdAt: 'June 02, 2001 02:11 AM',
    lastActivityAt: '2 hours ago',
    tags: ['absence', 'relationships', 'waiting'],
    reactions: reactions(54, 8, 30, 41, 4),
    replyCount: 12,
    viewCount: 731,
    authorHandle: 'anonymous',
    authorId: 'ghost-013',
    seal: 'soft',
  },
  {
    id: 'cf-002',
    type: 'CONFESSION',
    category: 'Addiction Recovery',
    title: 'I keep the number disconnected on purpose',
    body:
      'The disconnected number is the only thing that keeps me from calling the real person. I call the dead line instead and listen to nothing until the urge passes.',
    excerpt: 'I call the dead line instead and listen to nothing until the urge passes.',
    createdAt: 'September 14, 2001 04:22 AM',
    lastActivityAt: '1 day ago',
    tags: ['recovery', 'phone', 'ritual'],
    reactions: reactions(36, 5, 21, 29, 3),
    replyCount: 8,
    viewCount: 509,
    authorHandle: 'anonymous',
    authorId: 'ghost-014',
    seal: 'buried',
  },
];

export const DREAM_FILE_SEED: DreamFileContent[] = [
  {
    id: 'dr-001',
    type: 'DREAM_FILE',
    category: 'Dreams',
    title: 'Dream File 08: fluorescent stairs below the archive',
    body:
      '> stairwell was wet\n> lights buzzed in groups of three\n> bottom floor had message boards where paper should be\n\nwoke up with the smell of bleach and static.',
    excerpt: 'fluorescent stairs below the archive',
    createdAt: 'May 21, 2026 03:14 AM',
    lastActivityAt: '6 hours ago',
    tags: ['stairs', 'archive', 'bleach'],
    reactions: reactions(25, 6, 18, 11, 1),
    replyCount: 17,
    viewCount: 688,
    authorHandle: 'sleeprelay',
    authorId: 'ghost-003',
    dreamIndex: 'DF-08',
    sleepPhase: 'REM',
  },
];

export const THEORY_SEED: TheoryContent[] = [
  {
    id: 'ty-001',
    type: 'THEORY',
    category: 'Simulation Theory',
    title: 'Deletion is a visibility state, not an ending',
    body:
      'Archive behavior suggests removal changes who can see a record, not whether the record exists. We may be living inside permission edits.',
    excerpt: 'deletion changes who can see a record',
    createdAt: 'May 20, 2026 12:08 AM',
    lastActivityAt: '34 min ago',
    tags: ['deletion', 'visibility', 'permissions'],
    reactions: reactions(47, 19, 25, 18, 4),
    replyCount: 63,
    viewCount: 1880,
    authorHandle: 'glitchdiet',
    authorId: 'ghost-015',
    theoryStatus: 'active',
  },
  {
    id: 'ty-002',
    type: 'THEORY',
    category: 'Shadow Systems',
    title: 'The city has parallel paperwork for public-facing and internal reality',
    body:
      'Treating this as speculation built from mismatched forms, copied stamps, and stories from night staff. The theory is about administrative folklore, not action.',
    excerpt: 'speculative theory built from mismatched forms and night-shift stories',
    createdAt: 'May 19, 2026 01:52 AM',
    lastActivityAt: '3 hours ago',
    tags: ['paperwork', 'night staff', 'speculation'],
    reactions: reactions(34, 10, 17, 15, 4),
    replyCount: 44,
    viewCount: 1672,
    authorHandle: 'ledgerghost',
    authorId: 'ghost-002',
    theoryStatus: 'active',
  },
  {
    id: 'ty-003',
    type: 'THEORY',
    category: 'Black Projects',
    title: 'Hangar ghost stories always start with the same missing hour',
    body:
      'Collected as folklore from retirees, cousins, and overnight mechanics. We keep it framed as oral history and rumor because that is what it is.',
    excerpt: 'oral-history rumors about a recurring missing hour',
    createdAt: 'May 17, 2026 02:06 AM',
    lastActivityAt: '7 hours ago',
    tags: ['oral history', 'hangar', 'missing hour'],
    reactions: reactions(27, 8, 12, 13, 2),
    replyCount: 29,
    viewCount: 1214,
    authorHandle: 'northdrift_anon',
    authorId: 'ghost-001',
    theoryStatus: 'contested',
  },
  {
    id: 'ty-004',
    type: 'THEORY',
    category: 'Psyops',
    title: 'The poster campaign may have been designed to feel half-remembered',
    body:
      'This board keeps it in the realm of media analysis and collective memory. Nobody here is claiming proof, only comparing recurring motifs.',
    excerpt: 'media-analysis thread about recurring motifs and engineered déjà vu',
    createdAt: 'May 16, 2026 11:51 PM',
    lastActivityAt: '6 hours ago',
    tags: ['posters', 'media analysis', 'motifs'],
    reactions: reactions(23, 5, 14, 9, 3),
    replyCount: 26,
    viewCount: 1047,
    authorHandle: 'nighteditor',
    authorId: 'ghost-016',
    theoryStatus: 'active',
  },
];

export const LOST_MEDIA_SEED: ForumContent[] = [
  {
    id: 'lm-001',
    type: 'LOST_MEDIA',
    category: 'Lost Media',
    title: 'Motel Channel 6 audio block from 2001',
    body:
      'Recovered from a mislabeled DAT. Quiet at first, then a voice reading usernames that do not appear anywhere public.',
    excerpt: 'voice reading usernames that do not appear anywhere public',
    createdAt: 'May 18, 2026 11:09 PM',
    lastActivityAt: '12 min ago',
    tags: ['audio', 'dat', 'motel'],
    reactions: reactions(39, 11, 16, 12, 2),
    replyCount: 24,
    viewCount: 1156,
    authorHandle: 'coppermodem',
    authorId: 'ghost-005',
    mediaFormat: 'audio',
  },
  {
    id: 'lm-002',
    type: 'LOST_MEDIA',
    category: 'Internet Mysteries',
    title: 'Archive of broken homepage screenshots with no known source domain',
    body:
      'A gallery of homepage captures from a site nobody can place. We are cataloging aesthetics, timestamps, and recurring text fragments only.',
    excerpt: 'broken homepage screenshots from an unplaced source domain',
    createdAt: 'May 18, 2026 01:44 AM',
    lastActivityAt: '2 hours ago',
    tags: ['screenshots', 'unknown site', 'catalog'],
    reactions: reactions(32, 7, 15, 11, 2),
    replyCount: 28,
    viewCount: 1331,
    authorHandle: 'coppermodem',
    authorId: 'ghost-005',
    mediaFormat: 'site',
  },
  {
    id: 'lm-003',
    type: 'LOST_MEDIA',
    category: 'Occult Archives',
    title: 'Photocopies of a ritual zine with half the pages missing',
    body:
      'Archived as underground print culture, not instructions. Discussion stays focused on symbolism, design language, and provenance.',
    excerpt: 'underground print artifact discussed for symbolism and provenance',
    createdAt: 'May 14, 2026 03:02 AM',
    lastActivityAt: '1 day ago',
    tags: ['zine', 'symbolism', 'print culture'],
    reactions: reactions(19, 4, 12, 10, 1),
    replyCount: 16,
    viewCount: 780,
    authorHandle: 'ashtrayoracle',
    authorId: 'ghost-006',
    mediaFormat: 'scan',
  },
];

export const SIGNAL_SEED: SignalContent[] = [
  {
    id: 'sg-001',
    type: 'SIGNAL',
    category: 'Technology',
    title: 'Signal detected on 89.3 MHz',
    body: 'CONNECTION STABLE. ARCHIVE DEPTH: UNKNOWN.',
    excerpt: 'CONNECTION STABLE. ARCHIVE DEPTH: UNKNOWN.',
    createdAt: 'May 23, 2026 03:11 AM',
    lastActivityAt: 'just now',
    tags: ['frequency', 'status'],
    reactions: reactions(9, 0, 3, 7, 6),
    replyCount: 0,
    viewCount: 201,
    authorHandle: 'system',
    authorId: 'ghost-sys',
    frequency: '89.3 MHz',
    source: 'relay north',
  },
  {
    id: 'sg-002',
    type: 'SIGNAL',
    category: 'AI',
    title: 'Signal detected on 96.3 MHz',
    body: 'NEW NODE CONNECTED. LOCATION: UNKNOWN.',
    excerpt: 'NEW NODE CONNECTED. LOCATION: UNKNOWN.',
    createdAt: 'May 23, 2026 03:17 AM',
    lastActivityAt: '3 min ago',
    tags: ['node', 'presence'],
    reactions: reactions(14, 1, 7, 10, 9),
    replyCount: 0,
    viewCount: 288,
    authorHandle: 'system',
    authorId: 'ghost-sys',
    frequency: '96.3 MHz',
    source: 'presence scanner',
  },
  {
    id: 'sg-003',
    type: 'SIGNAL',
    category: 'Hidden History',
    title: 'Signal detected on 98.6 MHz',
    body: 'RECOVERED ENTRY: [HIDDEN-HISTORY/0x4A2C] REINDEXED.',
    excerpt: 'RECOVERED ENTRY REINDEXED.',
    createdAt: 'May 23, 2026 03:21 AM',
    lastActivityAt: '8 min ago',
    tags: ['recovered', 'archive'],
    reactions: reactions(11, 0, 6, 8, 6),
    replyCount: 0,
    viewCount: 184,
    authorHandle: 'system',
    authorId: 'ghost-sys',
    frequency: '98.6 MHz',
    source: 'archive relay',
  },
  {
    id: 'sg-004',
    type: 'SIGNAL',
    category: 'Corporate Secrets',
    title: 'Signal detected on 101.1 MHz',
    body: 'INTERNAL MEMO FRAGMENT MOVED TO LORE INDEX. DISCUSSION MODE ONLY.',
    excerpt: 'internal memo fragment moved to lore index',
    createdAt: 'May 23, 2026 03:24 AM',
    lastActivityAt: '4 min ago',
    tags: ['memo', 'lore index'],
    reactions: reactions(7, 0, 5, 6, 7),
    replyCount: 0,
    viewCount: 143,
    authorHandle: 'system',
    authorId: 'ghost-sys',
    frequency: '101.1 MHz',
    source: 'lore relay',
  },
];

export const ENCOUNTER_SEED: EncounterContent[] = [
  {
    id: 'en-001',
    type: 'ENCOUNTER',
    category: 'Paranormal',
    title: 'The payphone outside the closed arcade',
    body: 'It rang once. Nobody was calling. Caller knew the last confirmed transaction.',
    excerpt: 'caller knew the transaction before I spoke',
    createdAt: 'May 23, 2026 03:04 AM',
    lastActivityAt: '1 hour ago',
    tags: ['payphone', 'arcade', 'call'],
    reactions: reactions(15, 4, 7, 12, 3),
    replyCount: 19,
    viewCount: 721,
    authorHandle: 'ashtrayoracle',
    authorId: 'ghost-006',
    coordinates: '40.7128 N, 74.0060 W',
    locationName: 'THE PAYPHONE',
  },
  {
    id: 'en-002',
    type: 'ENCOUNTER',
    category: 'UFOs',
    title: 'Signal tower that broadcasts on a dead frequency',
    body: 'Broadcast appears between 2 and 4 AM only. Nobody claims the transmitter.',
    excerpt: 'broadcast appears between 2 and 4 AM only',
    createdAt: 'May 22, 2026 02:22 AM',
    lastActivityAt: '5 hours ago',
    tags: ['tower', 'broadcast', 'night'],
    reactions: reactions(12, 3, 5, 6, 2),
    replyCount: 14,
    viewCount: 612,
    authorHandle: 'northdrift_anon',
    authorId: 'ghost-001',
    coordinates: '51.5074 N, 0.1278 W',
    locationName: 'THE SIGNAL TOWER',
  },
  {
    id: 'en-003',
    type: 'ENCOUNTER',
    category: 'Dreams',
    title: 'Transit node from the recurring station dream',
    body: 'Three separate posters mapped the same tile pattern without talking first.',
    excerpt: 'three separate posters mapped the same tile pattern',
    createdAt: 'May 20, 2026 03:48 AM',
    lastActivityAt: '2 days ago',
    tags: ['station', 'tile', 'shared dream'],
    reactions: reactions(17, 6, 11, 7, 1),
    replyCount: 21,
    viewCount: 830,
    authorHandle: 'sleeprelay',
    authorId: 'ghost-003',
    coordinates: '48.8566 N, 2.3522 E',
    locationName: 'THE TRANSIT NODE',
  },
  {
    id: 'en-004',
    type: 'ENCOUNTER',
    category: 'Unsolved Events',
    title: 'The street clock skipped 14 minutes for everyone on the block',
    body:
      'Shared here as a neighborhood story compiled from forum recollections. No suspects, no calls to action, just timestamps and memory overlap.',
    excerpt: 'forum recollections align on the same missing fourteen minutes',
    createdAt: 'May 18, 2026 11:58 PM',
    lastActivityAt: '9 hours ago',
    tags: ['clock', 'memory', 'block'],
    reactions: reactions(22, 5, 11, 8, 2),
    replyCount: 18,
    viewCount: 944,
    authorHandle: 'sleeprelay',
    authorId: 'ghost-003',
    coordinates: '39.7392 N, 104.9903 W',
    locationName: 'THE CLOCK BLOCK',
  },
];

export const LOG_SEED: LogContent[] = [
  {
    id: 'lg-001',
    type: 'LOG',
    category: 'Stories',
    title: 'Presence log',
    body: 'guest_184 entered /paranormal/ from a webtv user agent',
    excerpt: 'guest_184 entered /paranormal/ from a webtv user agent',
    createdAt: '03:11:07',
    lastActivityAt: '03:11:07',
    tags: ['presence'],
    reactions: reactions(0, 0, 0, 0, 0),
    replyCount: 0,
    viewCount: 0,
    authorHandle: 'system',
    authorId: 'ghost-sys',
    logKind: 'presence',
  },
  {
    id: 'lg-002',
    type: 'LOG',
    category: 'Lost Media',
    title: 'Recovery log',
    body: 'new attachment queued in /lost-media/: motel_channel_6.wav',
    excerpt: 'new attachment queued in /lost-media/: motel_channel_6.wav',
    createdAt: '03:12:44',
    lastActivityAt: '03:12:44',
    tags: ['archive'],
    reactions: reactions(0, 0, 0, 0, 0),
    replyCount: 0,
    viewCount: 0,
    authorHandle: 'system',
    authorId: 'ghost-sys',
    logKind: 'archive',
  },
  {
    id: 'lg-003',
    type: 'LOG',
    category: 'Politics',
    title: 'Mod log',
    body: 'board cooled after mirror thread split',
    excerpt: 'board cooled after mirror thread split',
    createdAt: '03:14:09',
    lastActivityAt: '03:14:09',
    tags: ['system'],
    reactions: reactions(0, 0, 0, 0, 0),
    replyCount: 0,
    viewCount: 0,
    authorHandle: 'system',
    authorId: 'ghost-sys',
    logKind: 'system',
  },
];

export const WORLD_EVENT_SEED: WorldEvent[] = [
  {
    id: 'we-001',
    timestamp: '03:11:07',
    message: 'signal detected in the north relay',
    type: 'signal_detected',
  },
  {
    id: 'we-002',
    timestamp: '03:14:44',
    message: 'recovered archive entry reindexed under hidden history',
    type: 'archive_recovered',
  },
  {
    id: 'we-003',
    timestamp: '03:17:22',
    message: 'new node connected from an unknown dial-in',
    type: 'node_connected',
  },
  {
    id: 'we-004',
    timestamp: '03:21:51',
    message: 'duplicate timestamp observed in /dreams/ and /ai/',
    type: 'system_notice',
  },
  {
    id: 'we-005',
    timestamp: '03:24:18',
    message: 'lore-only memo fragment indexed under /corporate-secrets/',
    type: 'archive_recovered',
  },
  {
    id: 'we-006',
    timestamp: '03:26:40',
    message: 'new node drifted into /dark-web-lore/ and started cataloging banners',
    type: 'node_connected',
  },
];

export const ARCHIVE_MESSAGES = [
  'mirror node 04 rebuilt after line noise took the index',
  'welcome thread restored from a partial 2001 scrape',
  'remember: no accounts, no ids, no social graph',
  'someone keeps posting tomorrow\'s timestamps two minutes early',
  'the archive remembers what deletions forget',
  'censored-history board reopened as a memory archive, not a claim engine',
  'forbidden-tech threads are cataloged as lore and design speculation only',
];

export const ONLINE_COUNTS = [219, 227, 233, 241, 247, 252, 244, 239];

export const CREATE_THREAD_DRAFT: CreateThreadDraft = {
  category: 'Stories',
  title: '',
  body: '',
  tags: ['late-night', 'anonymous'],
  imagePlaceholder: null,
};

export const SEEDED_CATEGORIES = CATEGORY_ORDER;

export const SEEDED_CONTENT: ForumContent[] = [
  ...THREAD_SEED,
  ...ARCHIVE_ENTRY_SEED,
  ...CONFESSION_SEED,
  ...DREAM_FILE_SEED,
  ...THEORY_SEED,
  ...LOST_MEDIA_SEED,
  ...SIGNAL_SEED,
  ...ENCOUNTER_SEED,
  ...LOG_SEED,
];
